/* This file was generated by SableCC (http://www.sablecc.org/). */

package jbehave.story.codegen.sablecc.parser;

import jbehave.story.codegen.sablecc.analysis.AnalysisAdapter;
import jbehave.story.codegen.sablecc.node.EOF;
import jbehave.story.codegen.sablecc.node.TAsA;
import jbehave.story.codegen.sablecc.node.TEndl;
import jbehave.story.codegen.sablecc.node.TIWant;
import jbehave.story.codegen.sablecc.node.TScenarioKeyword;
import jbehave.story.codegen.sablecc.node.TSoThat;
import jbehave.story.codegen.sablecc.node.TSpace;
import jbehave.story.codegen.sablecc.node.TTitleKeyword;
import jbehave.story.codegen.sablecc.node.TWord;


class TokenIndex extends AnalysisAdapter
{
    int index;

    public void caseTTitleKeyword(TTitleKeyword node)
    {
        index = 0;
    }

    public void caseTScenarioKeyword(TScenarioKeyword node)
    {
        index = 1;
    }

    public void caseTAsA(TAsA node)
    {
        index = 2;
    }

    public void caseTIWant(TIWant node)
    {
        index = 3;
    }

    public void caseTSoThat(TSoThat node)
    {
        index = 4;
    }

    public void caseTSpace(TSpace node)
    {
        index = 5;
    }

    public void caseTWord(TWord node)
    {
        index = 6;
    }

    public void caseTEndl(TEndl node)
    {
        index = 7;
    }

    public void caseEOF(EOF node)
    {
        index = 8;
    }
}
