/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.jbehave.core.story.codegen.sablecc.lexer;

import java.io.*;
import java.util.*;
import org.jbehave.core.story.codegen.sablecc.node.*;

public class Lexer
{
    protected Token token;
    protected State state = State.INITIAL;

    private PushbackReader in;
    private int line;
    private int pos;
    private boolean cr;
    private boolean eof;
    private final StringBuffer text = new StringBuffer();

    protected void filter() throws LexerException, IOException
    {
    }

    public Lexer(PushbackReader in)
    {
        this.in = in;
    }
 
    public Token peek() throws LexerException, IOException
    {
        while(token == null)
        {
            token = getToken();
            filter();
        }

        return token;
    }

    public Token next() throws LexerException, IOException
    {
        while(token == null)
        {
            token = getToken();
            filter();
        }

        Token result = token;
        token = null;
        return result;
    }

    protected Token getToken() throws IOException, LexerException
    {
        int dfa_state = 0;

        int start_pos = pos;
        int start_line = line;

        int accept_state = -1;
        int accept_token = -1;
        int accept_length = -1;
        int accept_pos = -1;
        int accept_line = -1;

        int[][][] gotoTable = this.gotoTable[state.id()];
        int[] accept = this.accept[state.id()];
        text.setLength(0);

        while(true)
        {
            int c = getChar();

            if(c != -1)
            {
                switch(c)
                {
                case 10:
                    if(cr)
                    {
                        cr = false;
                    }
                    else
                    {
                        line++;
                        pos = 0;
                    }
                    break;
                case 13:
                    line++;
                    pos = 0;
                    cr = true;
                    break;
                default:
                    pos++;
                    cr = false;
                    break;
                };

                text.append((char) c);

                do
                {
                    int oldState = (dfa_state < -1) ? (-2 -dfa_state) : dfa_state;

                    dfa_state = -1;

                    int[][] tmp1 =  gotoTable[oldState];
                    int low = 0;
                    int high = tmp1.length - 1;

                    while(low <= high)
                    {
                        int middle = (low + high) / 2;
                        int[] tmp2 = tmp1[middle];

                        if(c < tmp2[0])
                        {
                            high = middle - 1;
                        }
                        else if(c > tmp2[1])
                        {
                            low = middle + 1;
                        }
                        else
                        {
                            dfa_state = tmp2[2];
                            break;
                        }
                    }
                }while(dfa_state < -1);
            }
            else
            {
                dfa_state = -1;
            }

            if(dfa_state >= 0)
            {
                if(accept[dfa_state] != -1)
                {
                    accept_state = dfa_state;
                    accept_token = accept[dfa_state];
                    accept_length = text.length();
                    accept_pos = pos;
                    accept_line = line;
                }
            }
            else
            {
                if(accept_state != -1)
                {
                    switch(accept_token)
                    {
                    case 0:
                        {
                            Token token = new0(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 1:
                        {
                            Token token = new1(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 2:
                        {
                            Token token = new2(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 3:
                        {
                            Token token = new3(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 4:
                        {
                            Token token = new4(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 5:
                        {
                            Token token = new5(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 6:
                        {
                            Token token = new6(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 7:
                        {
                            Token token = new7(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 8:
                        {
                            Token token = new8(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 9:
                        {
                            Token token = new9(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 10:
                        {
                            Token token = new10(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 11:
                        {
                            Token token = new11(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 12:
                        {
                            Token token = new12(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 13:
                        {
                            Token token = new13(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    }
                }
                else
                {
                    if(text.length() > 0)
                    {
                        throw new LexerException(
                            "[" + (start_line + 1) + "," + (start_pos + 1) + "]" +
                            " Unknown token: " + text);
                    }
                    else
                    {
                        EOF token = new EOF(
                            start_line + 1,
                            start_pos + 1);
                        return token;
                    }
                }
            }
        }
    }

    Token new0(int line, int pos) { return new TTitleKeyword(line, pos); }
    Token new1(int line, int pos) { return new TPackageKeyword(line, pos); }
    Token new2(int line, int pos) { return new TScenarioKeyword(line, pos); }
    Token new3(int line, int pos) { return new TAsA(line, pos); }
    Token new4(int line, int pos) { return new TIWant(line, pos); }
    Token new5(int line, int pos) { return new TSoThat(line, pos); }
    Token new6(int line, int pos) { return new TGiven(line, pos); }
    Token new7(int line, int pos) { return new TWhen(line, pos); }
    Token new8(int line, int pos) { return new TThen(line, pos); }
    Token new9(String text, int line, int pos) { return new TSpace(text, line, pos); }
    Token new10(String text, int line, int pos) { return new TWord(text, line, pos); }
    Token new11(String text, int line, int pos) { return new TPackageName(text, line, pos); }
    Token new12(String text, int line, int pos) { return new TEndl(text, line, pos); }
    Token new13(String text, int line, int pos) { return new TCommentline(text, line, pos); }

    private int getChar() throws IOException
    {
        if(eof)
        {
            return -1;
        }

        int result = in.read();

        if(result == -1)
        {
            eof = true;
        }

        return result;
    }

    private void pushBack(int acceptLength) throws IOException
    {
        int length = text.length();
        for(int i = length - 1; i >= acceptLength; i--)
        {
            eof = false;

            in.unread(text.charAt(i));
        }
    }

    protected void unread(Token token) throws IOException
    {
        String text = token.getText();
        int length = text.length();

        for(int i = length - 1; i >= 0; i--)
        {
            eof = false;

            in.unread(text.charAt(i));
        }

        pos = token.getPos() - 1;
        line = token.getLine() - 1;
    }

    private String getText(int acceptLength)
    {
        StringBuffer s = new StringBuffer(acceptLength);
        for(int i = 0; i < acceptLength; i++)
        {
            s.append(text.charAt(i));
        }

        return s.toString();
    }

    private static int[][][][] gotoTable;
/*  {
        { // INITIAL
            {{10, 10, 1}, {13, 13, 2}, {32, 32, 3}, {35, 35, 4}, {45, 45, 5}, {46, 46, 6}, {48, 57, 7}, {65, 65, 8}, {66, 70, 9}, {71, 71, 10}, {72, 72, 9}, {73, 73, 11}, {74, 79, 9}, {80, 80, 12}, {81, 82, 9}, {83, 83, 13}, {84, 84, 14}, {85, 86, 9}, {87, 87, 15}, {88, 90, 9}, {97, 122, 9}, },
            {},
            {{10, 10, 16}, },
            {},
            {{9, 9, 17}, {10, 10, 18}, {13, 13, 19}, {32, 32, 20}, {40, 40, 21}, {41, 41, 22}, {42, 42, 23}, {45, 45, 24}, {46, 46, 25}, {47, 47, 26}, {48, 57, 27}, {63, 63, 28}, {65, 90, 29}, {97, 122, 29}, {197, 197, 30}, {198, 198, 31}, {216, 216, 32}, {229, 229, 33}, {230, 230, 34}, {248, 248, 35}, },
            {{45, 57, -2}, {65, 90, 36}, {97, 122, 36}, },
            {{45, 122, -7}, },
            {{45, 122, -7}, },
            {{45, 57, -2}, {65, 90, 9}, {97, 114, 9}, {115, 115, 37}, {116, 122, 9}, },
            {{45, 90, -10}, {97, 122, 9}, },
            {{45, 90, -10}, {97, 104, 9}, {105, 105, 38}, {106, 122, 9}, },
            {{32, 32, 39}, {45, 122, -11}, },
            {{45, 90, -10}, {97, 97, 40}, {98, 122, 9}, },
            {{45, 90, -10}, {97, 98, 9}, {99, 99, 41}, {100, 110, 9}, {111, 111, 42}, {112, 122, 9}, },
            {{45, 90, -10}, {97, 103, 9}, {104, 104, 43}, {105, 105, 44}, {106, 122, 9}, },
            {{45, 103, -16}, {104, 104, 45}, {105, 122, 9}, },
            {},
            {{9, 248, -6}, },
            {},
            {{10, 10, 46}, },
            {{9, 248, -6}, },
            {{9, 248, -6}, },
            {{9, 248, -6}, },
            {{9, 248, -6}, },
            {{9, 248, -6}, },
            {{9, 248, -6}, },
            {{9, 248, -6}, },
            {{9, 248, -6}, },
            {{9, 248, -6}, },
            {{9, 248, -6}, },
            {{9, 248, -6}, },
            {{9, 248, -6}, },
            {{9, 248, -6}, },
            {{9, 248, -6}, },
            {{9, 248, -6}, },
            {{9, 248, -6}, },
            {{45, 122, -7}, },
            {{32, 32, 47}, {45, 122, -11}, },
            {{45, 90, -10}, {97, 117, 9}, {118, 118, 48}, {119, 122, 9}, },
            {{119, 119, 49}, },
            {{45, 98, -15}, {99, 99, 50}, {100, 122, 9}, },
            {{45, 90, -10}, {97, 100, 9}, {101, 101, 51}, {102, 122, 9}, },
            {{32, 32, 52}, {45, 122, -11}, },
            {{45, 100, -43}, {101, 101, 53}, {102, 122, 9}, },
            {{45, 90, -10}, {97, 115, 9}, {116, 116, 54}, {117, 122, 9}, },
            {{45, 100, -43}, {101, 101, 55}, {102, 122, 9}, },
            {},
            {{97, 97, 56}, },
            {{45, 100, -43}, {101, 101, 57}, {102, 122, 9}, },
            {{97, 97, 58}, },
            {{45, 90, -10}, {97, 106, 9}, {107, 107, 59}, {108, 122, 9}, },
            {{45, 90, -10}, {97, 109, 9}, {110, 110, 60}, {111, 122, 9}, },
            {{116, 116, 61}, },
            {{45, 109, -53}, {110, 110, 62}, {111, 122, 9}, },
            {{45, 90, -10}, {97, 107, 9}, {108, 108, 63}, {109, 122, 9}, },
            {{45, 109, -53}, {110, 110, 64}, {111, 122, 9}, },
            {},
            {{45, 109, -53}, {110, 110, 65}, {111, 122, 9}, },
            {{110, 110, 66}, },
            {{45, 90, -10}, {97, 97, 67}, {98, 122, 9}, },
            {{45, 90, -10}, {97, 97, 68}, {98, 122, 9}, },
            {{104, 104, 69}, },
            {{45, 122, -11}, },
            {{45, 100, -43}, {101, 101, 70}, {102, 122, 9}, },
            {{45, 122, -11}, },
            {{45, 122, -11}, },
            {{116, 116, 71}, },
            {{45, 90, -10}, {97, 102, 9}, {103, 103, 72}, {104, 122, 9}, },
            {{45, 90, -10}, {97, 113, 9}, {114, 114, 73}, {115, 122, 9}, },
            {{97, 97, 74}, },
            {{45, 57, -2}, {58, 58, 75}, {65, 122, -11}, },
            {},
            {{45, 100, -43}, {101, 101, 76}, {102, 122, 9}, },
            {{45, 104, -12}, {105, 105, 77}, {106, 122, 9}, },
            {{116, 116, 78}, },
            {},
            {{45, 57, -2}, {58, 58, 79}, {65, 122, -11}, },
            {{45, 90, -10}, {97, 110, 9}, {111, 111, 80}, {112, 122, 9}, },
            {},
            {},
            {{45, 57, -2}, {58, 58, 81}, {65, 122, -11}, },
            {},
        }
    };*/

    private static int[][] accept;
/*  {
        // INITIAL
        {-1, 12, 12, 9, -1, 11, 11, 11, 10, 10, 10, 10, 10, 10, 10, 10, 12, -1, 13, 13, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 11, 10, 10, -1, 10, 10, 10, 10, 10, 10, 13, -1, 10, -1, 10, 10, -1, 10, 10, 10, 3, 10, -1, 10, 10, -1, 8, 10, 7, 6, -1, 10, 10, -1, 10, 4, 10, 10, -1, 0, 10, 10, 5, 1, 10, 2, },

    };*/

    public static class State
    {
        public final static State INITIAL = new State(0);

        private int id;

        private State(int id)
        {
            this.id = id;
        }

        public int id()
        {
            return id;
        }
    }

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Lexer.class.getResourceAsStream("lexer.dat")));

            // read gotoTable
            int length = s.readInt();
            gotoTable = new int[length][][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][][];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                    length = s.readInt();
                    gotoTable[i][j] = new int[length][3];
                    for(int k = 0; k < gotoTable[i][j].length; k++)
                    {
                        for(int l = 0; l < 3; l++)
                        {
                            gotoTable[i][j][k][l] = s.readInt();
                        }
                    }
                }
            }

            // read accept
            length = s.readInt();
            accept = new int[length][];
            for(int i = 0; i < accept.length; i++)
            {
                length = s.readInt();
                accept[i] = new int[length];
                for(int j = 0; j < accept[i].length; j++)
                {
                    accept[i][j] = s.readInt();
                }
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"lexer.dat\" is either missing or corrupted.");
        }
    }
}
