/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.jbehave.core.story.codegen.sablecc.parser;

import org.jbehave.core.story.codegen.sablecc.lexer.*;
import org.jbehave.core.story.codegen.sablecc.node.*;
import org.jbehave.core.story.codegen.sablecc.analysis.*;
import java.util.*;

import java.io.DataInputStream;
import java.io.BufferedInputStream;
import java.io.IOException;

public class Parser
{
    public final Analysis ignoredTokens = new AnalysisAdapter();

    protected ArrayList nodeList;

    private final Lexer lexer;
    private final ListIterator stack = new LinkedList().listIterator();
    private int last_shift;
    private int last_pos;
    private int last_line;
    private Token last_token;
    private final TokenIndex converter = new TokenIndex();
    private final int[] action = new int[2];

    private final static int SHIFT = 0;
    private final static int REDUCE = 1;
    private final static int ACCEPT = 2;
    private final static int ERROR = 3;

    public Parser(Lexer lexer)
    {
        this.lexer = lexer;
    }

    protected void filter() throws ParserException, LexerException, IOException
    {
    }

    private void push(int numstate, ArrayList listNode, boolean hidden) throws ParserException, LexerException, IOException
    {
	this.nodeList = listNode;

        if(!hidden)
        {
            filter();
        }

        if(!stack.hasNext())
        {
            stack.add(new State(numstate, this.nodeList));
            return;
        }

        State s = (State) stack.next();
        s.state = numstate;
        s.nodes = this.nodeList;
    }

    private int goTo(int index)
    {
        int state = state();
        int low = 1;
        int high = gotoTable[index].length - 1;
        int value = gotoTable[index][0][1];

        while(low <= high)
        {
            int middle = (low + high) / 2;

            if(state < gotoTable[index][middle][0])
            {
                high = middle - 1;
            }
            else if(state > gotoTable[index][middle][0])
            {
                low = middle + 1;
            }
            else
            {
                value = gotoTable[index][middle][1];
                break;
            }
        }

        return value;
    }

    private int state()
    {
        State s = (State) stack.previous();
        stack.next();
        return s.state;
    }

    private ArrayList pop()
    {
        return (ArrayList) ((State) stack.previous()).nodes;
    }

    private int index(Switchable token)
    {
        converter.index = -1;
        token.apply(converter);
        return converter.index;
    }

    public Start parse() throws ParserException, LexerException, IOException
    {
        push(0, null, true);
        List ign = null;
        while(true)
        {
            while(index(lexer.peek()) == -1)
            {
                if(ign == null)
                {
                    ign = new TypedLinkedList(NodeCast.instance);
                }

                ign.add(lexer.next());
            }

            if(ign != null)
            {
                ignoredTokens.setIn(lexer.peek(), ign);
                ign = null;
            }

            last_pos = lexer.peek().getPos();
            last_line = lexer.peek().getLine();
            last_token = lexer.peek();

            int index = index(lexer.peek());
            action[0] = actionTable[state()][0][1];
            action[1] = actionTable[state()][0][2];

            int low = 1;
            int high = actionTable[state()].length - 1;

            while(low <= high)
            {
                int middle = (low + high) / 2;

                if(index < actionTable[state()][middle][0])
                {
                    high = middle - 1;
                }
                else if(index > actionTable[state()][middle][0])
                {
                    low = middle + 1;
                }
                else
                {
                    action[0] = actionTable[state()][middle][1];
                    action[1] = actionTable[state()][middle][2];
                    break;
                }
            }

            switch(action[0])
            {
                case SHIFT:
		    {
		        ArrayList list = new ArrayList();
		        list.add(lexer.next());
                        push(action[1], list, false);
                        last_shift = action[1];
                    }
		    break;
                case REDUCE:
                    switch(action[1])
                    {
                    case 0: /* reduce AAstory1Story */
		    {
			ArrayList list = new0();
			push(goTo(0), list, false);
		    }
		    break;
                    case 1: /* reduce AAstory2Story */
		    {
			ArrayList list = new1();
			push(goTo(0), list, false);
		    }
		    break;
                    case 2: /* reduce AAstory3Story */
		    {
			ArrayList list = new2();
			push(goTo(0), list, false);
		    }
		    break;
                    case 3: /* reduce AAstory4Story */
		    {
			ArrayList list = new3();
			push(goTo(0), list, false);
		    }
		    break;
                    case 4: /* reduce AAstory5Story */
		    {
			ArrayList list = new4();
			push(goTo(0), list, false);
		    }
		    break;
                    case 5: /* reduce AAstory6Story */
		    {
			ArrayList list = new5();
			push(goTo(0), list, false);
		    }
		    break;
                    case 6: /* reduce AAstory7Story */
		    {
			ArrayList list = new6();
			push(goTo(0), list, false);
		    }
		    break;
                    case 7: /* reduce AAstory8Story */
		    {
			ArrayList list = new7();
			push(goTo(0), list, false);
		    }
		    break;
                    case 8: /* reduce AAstory9Story */
		    {
			ArrayList list = new8();
			push(goTo(0), list, false);
		    }
		    break;
                    case 9: /* reduce AAstory10Story */
		    {
			ArrayList list = new9();
			push(goTo(0), list, false);
		    }
		    break;
                    case 10: /* reduce AAstory11Story */
		    {
			ArrayList list = new10();
			push(goTo(0), list, false);
		    }
		    break;
                    case 11: /* reduce AAstory12Story */
		    {
			ArrayList list = new11();
			push(goTo(0), list, false);
		    }
		    break;
                    case 12: /* reduce AAstory13Story */
		    {
			ArrayList list = new12();
			push(goTo(0), list, false);
		    }
		    break;
                    case 13: /* reduce AAstory14Story */
		    {
			ArrayList list = new13();
			push(goTo(0), list, false);
		    }
		    break;
                    case 14: /* reduce AAstory15Story */
		    {
			ArrayList list = new14();
			push(goTo(0), list, false);
		    }
		    break;
                    case 15: /* reduce AAstory16Story */
		    {
			ArrayList list = new15();
			push(goTo(0), list, false);
		    }
		    break;
                    case 16: /* reduce AAstory17Story */
		    {
			ArrayList list = new16();
			push(goTo(0), list, false);
		    }
		    break;
                    case 17: /* reduce AAstory18Story */
		    {
			ArrayList list = new17();
			push(goTo(0), list, false);
		    }
		    break;
                    case 18: /* reduce AAstory19Story */
		    {
			ArrayList list = new18();
			push(goTo(0), list, false);
		    }
		    break;
                    case 19: /* reduce AAstory20Story */
		    {
			ArrayList list = new19();
			push(goTo(0), list, false);
		    }
		    break;
                    case 20: /* reduce AAstory21Story */
		    {
			ArrayList list = new20();
			push(goTo(0), list, false);
		    }
		    break;
                    case 21: /* reduce AAstory22Story */
		    {
			ArrayList list = new21();
			push(goTo(0), list, false);
		    }
		    break;
                    case 22: /* reduce AAstory23Story */
		    {
			ArrayList list = new22();
			push(goTo(0), list, false);
		    }
		    break;
                    case 23: /* reduce AAstory24Story */
		    {
			ArrayList list = new23();
			push(goTo(0), list, false);
		    }
		    break;
                    case 24: /* reduce AAstory25Story */
		    {
			ArrayList list = new24();
			push(goTo(0), list, false);
		    }
		    break;
                    case 25: /* reduce AAstory26Story */
		    {
			ArrayList list = new25();
			push(goTo(0), list, false);
		    }
		    break;
                    case 26: /* reduce AAstory27Story */
		    {
			ArrayList list = new26();
			push(goTo(0), list, false);
		    }
		    break;
                    case 27: /* reduce AAstory28Story */
		    {
			ArrayList list = new27();
			push(goTo(0), list, false);
		    }
		    break;
                    case 28: /* reduce AAstory29Story */
		    {
			ArrayList list = new28();
			push(goTo(0), list, false);
		    }
		    break;
                    case 29: /* reduce AAstory30Story */
		    {
			ArrayList list = new29();
			push(goTo(0), list, false);
		    }
		    break;
                    case 30: /* reduce AAstory31Story */
		    {
			ArrayList list = new30();
			push(goTo(0), list, false);
		    }
		    break;
                    case 31: /* reduce AAstory32Story */
		    {
			ArrayList list = new31();
			push(goTo(0), list, false);
		    }
		    break;
                    case 32: /* reduce ATitle */
		    {
			ArrayList list = new32();
			push(goTo(1), list, false);
		    }
		    break;
                    case 33: /* reduce APackage */
		    {
			ArrayList list = new33();
			push(goTo(2), list, false);
		    }
		    break;
                    case 34: /* reduce ARole */
		    {
			ArrayList list = new34();
			push(goTo(3), list, false);
		    }
		    break;
                    case 35: /* reduce AFeature */
		    {
			ArrayList list = new35();
			push(goTo(4), list, false);
		    }
		    break;
                    case 36: /* reduce ABenefit */
		    {
			ArrayList list = new36();
			push(goTo(5), list, false);
		    }
		    break;
                    case 37: /* reduce AAscenario1Scenario */
		    {
			ArrayList list = new37();
			push(goTo(6), list, false);
		    }
		    break;
                    case 38: /* reduce AAscenario2Scenario */
		    {
			ArrayList list = new38();
			push(goTo(6), list, false);
		    }
		    break;
                    case 39: /* reduce AAscenario3Scenario */
		    {
			ArrayList list = new39();
			push(goTo(6), list, false);
		    }
		    break;
                    case 40: /* reduce AAscenario4Scenario */
		    {
			ArrayList list = new40();
			push(goTo(6), list, false);
		    }
		    break;
                    case 41: /* reduce AAscenario5Scenario */
		    {
			ArrayList list = new41();
			push(goTo(6), list, false);
		    }
		    break;
                    case 42: /* reduce AAscenario6Scenario */
		    {
			ArrayList list = new42();
			push(goTo(6), list, false);
		    }
		    break;
                    case 43: /* reduce AAscenario7Scenario */
		    {
			ArrayList list = new43();
			push(goTo(6), list, false);
		    }
		    break;
                    case 44: /* reduce AAscenario8Scenario */
		    {
			ArrayList list = new44();
			push(goTo(6), list, false);
		    }
		    break;
                    case 45: /* reduce AScenarioTitle */
		    {
			ArrayList list = new45();
			push(goTo(7), list, false);
		    }
		    break;
                    case 46: /* reduce AContext */
		    {
			ArrayList list = new46();
			push(goTo(8), list, false);
		    }
		    break;
                    case 47: /* reduce AEvent */
		    {
			ArrayList list = new47();
			push(goTo(9), list, false);
		    }
		    break;
                    case 48: /* reduce AOutcome */
		    {
			ArrayList list = new48();
			push(goTo(10), list, false);
		    }
		    break;
                    case 49: /* reduce APhrase */
		    {
			ArrayList list = new49();
			push(goTo(11), list, false);
		    }
		    break;
                    case 50: /* reduce AWordWordOrSpace */
		    {
			ArrayList list = new50();
			push(goTo(12), list, false);
		    }
		    break;
                    case 51: /* reduce ASpaceWordOrSpace */
		    {
			ArrayList list = new51();
			push(goTo(12), list, false);
		    }
		    break;
                    case 52: /* reduce ATerminal$Scenario */
		    {
			ArrayList list = new52();
			push(goTo(13), list, true);
		    }
		    break;
                    case 53: /* reduce ANonTerminal$Scenario */
		    {
			ArrayList list = new53();
			push(goTo(13), list, true);
		    }
		    break;
                    case 54: /* reduce ATerminal$Context */
		    {
			ArrayList list = new54();
			push(goTo(14), list, true);
		    }
		    break;
                    case 55: /* reduce ANonTerminal$Context */
		    {
			ArrayList list = new55();
			push(goTo(14), list, true);
		    }
		    break;
                    case 56: /* reduce ATerminal$Outcome */
		    {
			ArrayList list = new56();
			push(goTo(15), list, true);
		    }
		    break;
                    case 57: /* reduce ANonTerminal$Outcome */
		    {
			ArrayList list = new57();
			push(goTo(15), list, true);
		    }
		    break;
                    case 58: /* reduce ATerminal$WordOrSpace */
		    {
			ArrayList list = new58();
			push(goTo(16), list, true);
		    }
		    break;
                    case 59: /* reduce ANonTerminal$WordOrSpace */
		    {
			ArrayList list = new59();
			push(goTo(16), list, true);
		    }
		    break;
                    }
                    break;
                case ACCEPT:
                    {
                        EOF node2 = (EOF) lexer.next();
                        PStory node1 = (PStory) ((ArrayList)pop()).get(0);
                        Start node = new Start(node1, node2);
                        return node;
                    }
                case ERROR:
                    throw new ParserException(last_token,
                        "[" + last_line + "," + last_pos + "] " +
                        errorMessages[errors[action[1]]]);
            }
        }
    }



    ArrayList new0() /* reduce AAstory1Story */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStory pstoryNode1;
        {
        PTitle ptitleNode2;
        Object nullNode3 = null;
        Object nullNode4 = null;
        Object nullNode5 = null;
        Object nullNode6 = null;
        TypedLinkedList listNode7 = new TypedLinkedList();
        ptitleNode2 = (PTitle)nodeArrayList1.get(0);
        {
        }

        pstoryNode1 = new AStory(ptitleNode2, null, null, null, null, listNode7);
        }
	nodeList.add(pstoryNode1);
        return nodeList;
    }



    ArrayList new1() /* reduce AAstory2Story */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStory pstoryNode1;
        {
        PTitle ptitleNode2;
        PPackage ppackageNode3;
        Object nullNode4 = null;
        Object nullNode5 = null;
        Object nullNode6 = null;
        TypedLinkedList listNode7 = new TypedLinkedList();
        ptitleNode2 = (PTitle)nodeArrayList1.get(0);
        ppackageNode3 = (PPackage)nodeArrayList2.get(0);
        {
        }

        pstoryNode1 = new AStory(ptitleNode2, ppackageNode3, null, null, null, listNode7);
        }
	nodeList.add(pstoryNode1);
        return nodeList;
    }



    ArrayList new2() /* reduce AAstory3Story */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStory pstoryNode1;
        {
        PTitle ptitleNode2;
        Object nullNode3 = null;
        PRole proleNode4;
        Object nullNode5 = null;
        Object nullNode6 = null;
        TypedLinkedList listNode7 = new TypedLinkedList();
        ptitleNode2 = (PTitle)nodeArrayList1.get(0);
        proleNode4 = (PRole)nodeArrayList2.get(0);
        {
        }

        pstoryNode1 = new AStory(ptitleNode2, null, proleNode4, null, null, listNode7);
        }
	nodeList.add(pstoryNode1);
        return nodeList;
    }



    ArrayList new3() /* reduce AAstory4Story */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStory pstoryNode1;
        {
        PTitle ptitleNode2;
        PPackage ppackageNode3;
        PRole proleNode4;
        Object nullNode5 = null;
        Object nullNode6 = null;
        TypedLinkedList listNode7 = new TypedLinkedList();
        ptitleNode2 = (PTitle)nodeArrayList1.get(0);
        ppackageNode3 = (PPackage)nodeArrayList2.get(0);
        proleNode4 = (PRole)nodeArrayList3.get(0);
        {
        }

        pstoryNode1 = new AStory(ptitleNode2, ppackageNode3, proleNode4, null, null, listNode7);
        }
	nodeList.add(pstoryNode1);
        return nodeList;
    }



    ArrayList new4() /* reduce AAstory5Story */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStory pstoryNode1;
        {
        PTitle ptitleNode2;
        Object nullNode3 = null;
        Object nullNode4 = null;
        PFeature pfeatureNode5;
        Object nullNode6 = null;
        TypedLinkedList listNode7 = new TypedLinkedList();
        ptitleNode2 = (PTitle)nodeArrayList1.get(0);
        pfeatureNode5 = (PFeature)nodeArrayList2.get(0);
        {
        }

        pstoryNode1 = new AStory(ptitleNode2, null, null, pfeatureNode5, null, listNode7);
        }
	nodeList.add(pstoryNode1);
        return nodeList;
    }



    ArrayList new5() /* reduce AAstory6Story */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStory pstoryNode1;
        {
        PTitle ptitleNode2;
        PPackage ppackageNode3;
        Object nullNode4 = null;
        PFeature pfeatureNode5;
        Object nullNode6 = null;
        TypedLinkedList listNode7 = new TypedLinkedList();
        ptitleNode2 = (PTitle)nodeArrayList1.get(0);
        ppackageNode3 = (PPackage)nodeArrayList2.get(0);
        pfeatureNode5 = (PFeature)nodeArrayList3.get(0);
        {
        }

        pstoryNode1 = new AStory(ptitleNode2, ppackageNode3, null, pfeatureNode5, null, listNode7);
        }
	nodeList.add(pstoryNode1);
        return nodeList;
    }



    ArrayList new6() /* reduce AAstory7Story */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStory pstoryNode1;
        {
        PTitle ptitleNode2;
        Object nullNode3 = null;
        PRole proleNode4;
        PFeature pfeatureNode5;
        Object nullNode6 = null;
        TypedLinkedList listNode7 = new TypedLinkedList();
        ptitleNode2 = (PTitle)nodeArrayList1.get(0);
        proleNode4 = (PRole)nodeArrayList2.get(0);
        pfeatureNode5 = (PFeature)nodeArrayList3.get(0);
        {
        }

        pstoryNode1 = new AStory(ptitleNode2, null, proleNode4, pfeatureNode5, null, listNode7);
        }
	nodeList.add(pstoryNode1);
        return nodeList;
    }



    ArrayList new7() /* reduce AAstory8Story */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStory pstoryNode1;
        {
        PTitle ptitleNode2;
        PPackage ppackageNode3;
        PRole proleNode4;
        PFeature pfeatureNode5;
        Object nullNode6 = null;
        TypedLinkedList listNode7 = new TypedLinkedList();
        ptitleNode2 = (PTitle)nodeArrayList1.get(0);
        ppackageNode3 = (PPackage)nodeArrayList2.get(0);
        proleNode4 = (PRole)nodeArrayList3.get(0);
        pfeatureNode5 = (PFeature)nodeArrayList4.get(0);
        {
        }

        pstoryNode1 = new AStory(ptitleNode2, ppackageNode3, proleNode4, pfeatureNode5, null, listNode7);
        }
	nodeList.add(pstoryNode1);
        return nodeList;
    }



    ArrayList new8() /* reduce AAstory9Story */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStory pstoryNode1;
        {
        PTitle ptitleNode2;
        Object nullNode3 = null;
        Object nullNode4 = null;
        Object nullNode5 = null;
        PBenefit pbenefitNode6;
        TypedLinkedList listNode7 = new TypedLinkedList();
        ptitleNode2 = (PTitle)nodeArrayList1.get(0);
        pbenefitNode6 = (PBenefit)nodeArrayList2.get(0);
        {
        }

        pstoryNode1 = new AStory(ptitleNode2, null, null, null, pbenefitNode6, listNode7);
        }
	nodeList.add(pstoryNode1);
        return nodeList;
    }



    ArrayList new9() /* reduce AAstory10Story */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStory pstoryNode1;
        {
        PTitle ptitleNode2;
        PPackage ppackageNode3;
        Object nullNode4 = null;
        Object nullNode5 = null;
        PBenefit pbenefitNode6;
        TypedLinkedList listNode7 = new TypedLinkedList();
        ptitleNode2 = (PTitle)nodeArrayList1.get(0);
        ppackageNode3 = (PPackage)nodeArrayList2.get(0);
        pbenefitNode6 = (PBenefit)nodeArrayList3.get(0);
        {
        }

        pstoryNode1 = new AStory(ptitleNode2, ppackageNode3, null, null, pbenefitNode6, listNode7);
        }
	nodeList.add(pstoryNode1);
        return nodeList;
    }



    ArrayList new10() /* reduce AAstory11Story */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStory pstoryNode1;
        {
        PTitle ptitleNode2;
        Object nullNode3 = null;
        PRole proleNode4;
        Object nullNode5 = null;
        PBenefit pbenefitNode6;
        TypedLinkedList listNode7 = new TypedLinkedList();
        ptitleNode2 = (PTitle)nodeArrayList1.get(0);
        proleNode4 = (PRole)nodeArrayList2.get(0);
        pbenefitNode6 = (PBenefit)nodeArrayList3.get(0);
        {
        }

        pstoryNode1 = new AStory(ptitleNode2, null, proleNode4, null, pbenefitNode6, listNode7);
        }
	nodeList.add(pstoryNode1);
        return nodeList;
    }



    ArrayList new11() /* reduce AAstory12Story */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStory pstoryNode1;
        {
        PTitle ptitleNode2;
        PPackage ppackageNode3;
        PRole proleNode4;
        Object nullNode5 = null;
        PBenefit pbenefitNode6;
        TypedLinkedList listNode7 = new TypedLinkedList();
        ptitleNode2 = (PTitle)nodeArrayList1.get(0);
        ppackageNode3 = (PPackage)nodeArrayList2.get(0);
        proleNode4 = (PRole)nodeArrayList3.get(0);
        pbenefitNode6 = (PBenefit)nodeArrayList4.get(0);
        {
        }

        pstoryNode1 = new AStory(ptitleNode2, ppackageNode3, proleNode4, null, pbenefitNode6, listNode7);
        }
	nodeList.add(pstoryNode1);
        return nodeList;
    }



    ArrayList new12() /* reduce AAstory13Story */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStory pstoryNode1;
        {
        PTitle ptitleNode2;
        Object nullNode3 = null;
        Object nullNode4 = null;
        PFeature pfeatureNode5;
        PBenefit pbenefitNode6;
        TypedLinkedList listNode7 = new TypedLinkedList();
        ptitleNode2 = (PTitle)nodeArrayList1.get(0);
        pfeatureNode5 = (PFeature)nodeArrayList2.get(0);
        pbenefitNode6 = (PBenefit)nodeArrayList3.get(0);
        {
        }

        pstoryNode1 = new AStory(ptitleNode2, null, null, pfeatureNode5, pbenefitNode6, listNode7);
        }
	nodeList.add(pstoryNode1);
        return nodeList;
    }



    ArrayList new13() /* reduce AAstory14Story */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStory pstoryNode1;
        {
        PTitle ptitleNode2;
        PPackage ppackageNode3;
        Object nullNode4 = null;
        PFeature pfeatureNode5;
        PBenefit pbenefitNode6;
        TypedLinkedList listNode7 = new TypedLinkedList();
        ptitleNode2 = (PTitle)nodeArrayList1.get(0);
        ppackageNode3 = (PPackage)nodeArrayList2.get(0);
        pfeatureNode5 = (PFeature)nodeArrayList3.get(0);
        pbenefitNode6 = (PBenefit)nodeArrayList4.get(0);
        {
        }

        pstoryNode1 = new AStory(ptitleNode2, ppackageNode3, null, pfeatureNode5, pbenefitNode6, listNode7);
        }
	nodeList.add(pstoryNode1);
        return nodeList;
    }



    ArrayList new14() /* reduce AAstory15Story */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStory pstoryNode1;
        {
        PTitle ptitleNode2;
        Object nullNode3 = null;
        PRole proleNode4;
        PFeature pfeatureNode5;
        PBenefit pbenefitNode6;
        TypedLinkedList listNode7 = new TypedLinkedList();
        ptitleNode2 = (PTitle)nodeArrayList1.get(0);
        proleNode4 = (PRole)nodeArrayList2.get(0);
        pfeatureNode5 = (PFeature)nodeArrayList3.get(0);
        pbenefitNode6 = (PBenefit)nodeArrayList4.get(0);
        {
        }

        pstoryNode1 = new AStory(ptitleNode2, null, proleNode4, pfeatureNode5, pbenefitNode6, listNode7);
        }
	nodeList.add(pstoryNode1);
        return nodeList;
    }



    ArrayList new15() /* reduce AAstory16Story */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStory pstoryNode1;
        {
        PTitle ptitleNode2;
        PPackage ppackageNode3;
        PRole proleNode4;
        PFeature pfeatureNode5;
        PBenefit pbenefitNode6;
        TypedLinkedList listNode7 = new TypedLinkedList();
        ptitleNode2 = (PTitle)nodeArrayList1.get(0);
        ppackageNode3 = (PPackage)nodeArrayList2.get(0);
        proleNode4 = (PRole)nodeArrayList3.get(0);
        pfeatureNode5 = (PFeature)nodeArrayList4.get(0);
        pbenefitNode6 = (PBenefit)nodeArrayList5.get(0);
        {
        }

        pstoryNode1 = new AStory(ptitleNode2, ppackageNode3, proleNode4, pfeatureNode5, pbenefitNode6, listNode7);
        }
	nodeList.add(pstoryNode1);
        return nodeList;
    }



    ArrayList new16() /* reduce AAstory17Story */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStory pstoryNode1;
        {
        PTitle ptitleNode2;
        Object nullNode3 = null;
        Object nullNode4 = null;
        Object nullNode5 = null;
        Object nullNode6 = null;
        TypedLinkedList listNode8 = new TypedLinkedList();
        ptitleNode2 = (PTitle)nodeArrayList1.get(0);
        {
        TypedLinkedList listNode7 = new TypedLinkedList();
        listNode7 = (TypedLinkedList)nodeArrayList2.get(0);
	if(listNode7 != null)
	{
	  listNode8.addAll(listNode7);
	}
        }

        pstoryNode1 = new AStory(ptitleNode2, null, null, null, null, listNode8);
        }
	nodeList.add(pstoryNode1);
        return nodeList;
    }



    ArrayList new17() /* reduce AAstory18Story */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStory pstoryNode1;
        {
        PTitle ptitleNode2;
        PPackage ppackageNode3;
        Object nullNode4 = null;
        Object nullNode5 = null;
        Object nullNode6 = null;
        TypedLinkedList listNode8 = new TypedLinkedList();
        ptitleNode2 = (PTitle)nodeArrayList1.get(0);
        ppackageNode3 = (PPackage)nodeArrayList2.get(0);
        {
        TypedLinkedList listNode7 = new TypedLinkedList();
        listNode7 = (TypedLinkedList)nodeArrayList3.get(0);
	if(listNode7 != null)
	{
	  listNode8.addAll(listNode7);
	}
        }

        pstoryNode1 = new AStory(ptitleNode2, ppackageNode3, null, null, null, listNode8);
        }
	nodeList.add(pstoryNode1);
        return nodeList;
    }



    ArrayList new18() /* reduce AAstory19Story */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStory pstoryNode1;
        {
        PTitle ptitleNode2;
        Object nullNode3 = null;
        PRole proleNode4;
        Object nullNode5 = null;
        Object nullNode6 = null;
        TypedLinkedList listNode8 = new TypedLinkedList();
        ptitleNode2 = (PTitle)nodeArrayList1.get(0);
        proleNode4 = (PRole)nodeArrayList2.get(0);
        {
        TypedLinkedList listNode7 = new TypedLinkedList();
        listNode7 = (TypedLinkedList)nodeArrayList3.get(0);
	if(listNode7 != null)
	{
	  listNode8.addAll(listNode7);
	}
        }

        pstoryNode1 = new AStory(ptitleNode2, null, proleNode4, null, null, listNode8);
        }
	nodeList.add(pstoryNode1);
        return nodeList;
    }



    ArrayList new19() /* reduce AAstory20Story */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStory pstoryNode1;
        {
        PTitle ptitleNode2;
        PPackage ppackageNode3;
        PRole proleNode4;
        Object nullNode5 = null;
        Object nullNode6 = null;
        TypedLinkedList listNode8 = new TypedLinkedList();
        ptitleNode2 = (PTitle)nodeArrayList1.get(0);
        ppackageNode3 = (PPackage)nodeArrayList2.get(0);
        proleNode4 = (PRole)nodeArrayList3.get(0);
        {
        TypedLinkedList listNode7 = new TypedLinkedList();
        listNode7 = (TypedLinkedList)nodeArrayList4.get(0);
	if(listNode7 != null)
	{
	  listNode8.addAll(listNode7);
	}
        }

        pstoryNode1 = new AStory(ptitleNode2, ppackageNode3, proleNode4, null, null, listNode8);
        }
	nodeList.add(pstoryNode1);
        return nodeList;
    }



    ArrayList new20() /* reduce AAstory21Story */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStory pstoryNode1;
        {
        PTitle ptitleNode2;
        Object nullNode3 = null;
        Object nullNode4 = null;
        PFeature pfeatureNode5;
        Object nullNode6 = null;
        TypedLinkedList listNode8 = new TypedLinkedList();
        ptitleNode2 = (PTitle)nodeArrayList1.get(0);
        pfeatureNode5 = (PFeature)nodeArrayList2.get(0);
        {
        TypedLinkedList listNode7 = new TypedLinkedList();
        listNode7 = (TypedLinkedList)nodeArrayList3.get(0);
	if(listNode7 != null)
	{
	  listNode8.addAll(listNode7);
	}
        }

        pstoryNode1 = new AStory(ptitleNode2, null, null, pfeatureNode5, null, listNode8);
        }
	nodeList.add(pstoryNode1);
        return nodeList;
    }



    ArrayList new21() /* reduce AAstory22Story */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStory pstoryNode1;
        {
        PTitle ptitleNode2;
        PPackage ppackageNode3;
        Object nullNode4 = null;
        PFeature pfeatureNode5;
        Object nullNode6 = null;
        TypedLinkedList listNode8 = new TypedLinkedList();
        ptitleNode2 = (PTitle)nodeArrayList1.get(0);
        ppackageNode3 = (PPackage)nodeArrayList2.get(0);
        pfeatureNode5 = (PFeature)nodeArrayList3.get(0);
        {
        TypedLinkedList listNode7 = new TypedLinkedList();
        listNode7 = (TypedLinkedList)nodeArrayList4.get(0);
	if(listNode7 != null)
	{
	  listNode8.addAll(listNode7);
	}
        }

        pstoryNode1 = new AStory(ptitleNode2, ppackageNode3, null, pfeatureNode5, null, listNode8);
        }
	nodeList.add(pstoryNode1);
        return nodeList;
    }



    ArrayList new22() /* reduce AAstory23Story */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStory pstoryNode1;
        {
        PTitle ptitleNode2;
        Object nullNode3 = null;
        PRole proleNode4;
        PFeature pfeatureNode5;
        Object nullNode6 = null;
        TypedLinkedList listNode8 = new TypedLinkedList();
        ptitleNode2 = (PTitle)nodeArrayList1.get(0);
        proleNode4 = (PRole)nodeArrayList2.get(0);
        pfeatureNode5 = (PFeature)nodeArrayList3.get(0);
        {
        TypedLinkedList listNode7 = new TypedLinkedList();
        listNode7 = (TypedLinkedList)nodeArrayList4.get(0);
	if(listNode7 != null)
	{
	  listNode8.addAll(listNode7);
	}
        }

        pstoryNode1 = new AStory(ptitleNode2, null, proleNode4, pfeatureNode5, null, listNode8);
        }
	nodeList.add(pstoryNode1);
        return nodeList;
    }



    ArrayList new23() /* reduce AAstory24Story */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStory pstoryNode1;
        {
        PTitle ptitleNode2;
        PPackage ppackageNode3;
        PRole proleNode4;
        PFeature pfeatureNode5;
        Object nullNode6 = null;
        TypedLinkedList listNode8 = new TypedLinkedList();
        ptitleNode2 = (PTitle)nodeArrayList1.get(0);
        ppackageNode3 = (PPackage)nodeArrayList2.get(0);
        proleNode4 = (PRole)nodeArrayList3.get(0);
        pfeatureNode5 = (PFeature)nodeArrayList4.get(0);
        {
        TypedLinkedList listNode7 = new TypedLinkedList();
        listNode7 = (TypedLinkedList)nodeArrayList5.get(0);
	if(listNode7 != null)
	{
	  listNode8.addAll(listNode7);
	}
        }

        pstoryNode1 = new AStory(ptitleNode2, ppackageNode3, proleNode4, pfeatureNode5, null, listNode8);
        }
	nodeList.add(pstoryNode1);
        return nodeList;
    }



    ArrayList new24() /* reduce AAstory25Story */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStory pstoryNode1;
        {
        PTitle ptitleNode2;
        Object nullNode3 = null;
        Object nullNode4 = null;
        Object nullNode5 = null;
        PBenefit pbenefitNode6;
        TypedLinkedList listNode8 = new TypedLinkedList();
        ptitleNode2 = (PTitle)nodeArrayList1.get(0);
        pbenefitNode6 = (PBenefit)nodeArrayList2.get(0);
        {
        TypedLinkedList listNode7 = new TypedLinkedList();
        listNode7 = (TypedLinkedList)nodeArrayList3.get(0);
	if(listNode7 != null)
	{
	  listNode8.addAll(listNode7);
	}
        }

        pstoryNode1 = new AStory(ptitleNode2, null, null, null, pbenefitNode6, listNode8);
        }
	nodeList.add(pstoryNode1);
        return nodeList;
    }



    ArrayList new25() /* reduce AAstory26Story */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStory pstoryNode1;
        {
        PTitle ptitleNode2;
        PPackage ppackageNode3;
        Object nullNode4 = null;
        Object nullNode5 = null;
        PBenefit pbenefitNode6;
        TypedLinkedList listNode8 = new TypedLinkedList();
        ptitleNode2 = (PTitle)nodeArrayList1.get(0);
        ppackageNode3 = (PPackage)nodeArrayList2.get(0);
        pbenefitNode6 = (PBenefit)nodeArrayList3.get(0);
        {
        TypedLinkedList listNode7 = new TypedLinkedList();
        listNode7 = (TypedLinkedList)nodeArrayList4.get(0);
	if(listNode7 != null)
	{
	  listNode8.addAll(listNode7);
	}
        }

        pstoryNode1 = new AStory(ptitleNode2, ppackageNode3, null, null, pbenefitNode6, listNode8);
        }
	nodeList.add(pstoryNode1);
        return nodeList;
    }



    ArrayList new26() /* reduce AAstory27Story */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStory pstoryNode1;
        {
        PTitle ptitleNode2;
        Object nullNode3 = null;
        PRole proleNode4;
        Object nullNode5 = null;
        PBenefit pbenefitNode6;
        TypedLinkedList listNode8 = new TypedLinkedList();
        ptitleNode2 = (PTitle)nodeArrayList1.get(0);
        proleNode4 = (PRole)nodeArrayList2.get(0);
        pbenefitNode6 = (PBenefit)nodeArrayList3.get(0);
        {
        TypedLinkedList listNode7 = new TypedLinkedList();
        listNode7 = (TypedLinkedList)nodeArrayList4.get(0);
	if(listNode7 != null)
	{
	  listNode8.addAll(listNode7);
	}
        }

        pstoryNode1 = new AStory(ptitleNode2, null, proleNode4, null, pbenefitNode6, listNode8);
        }
	nodeList.add(pstoryNode1);
        return nodeList;
    }



    ArrayList new27() /* reduce AAstory28Story */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStory pstoryNode1;
        {
        PTitle ptitleNode2;
        PPackage ppackageNode3;
        PRole proleNode4;
        Object nullNode5 = null;
        PBenefit pbenefitNode6;
        TypedLinkedList listNode8 = new TypedLinkedList();
        ptitleNode2 = (PTitle)nodeArrayList1.get(0);
        ppackageNode3 = (PPackage)nodeArrayList2.get(0);
        proleNode4 = (PRole)nodeArrayList3.get(0);
        pbenefitNode6 = (PBenefit)nodeArrayList4.get(0);
        {
        TypedLinkedList listNode7 = new TypedLinkedList();
        listNode7 = (TypedLinkedList)nodeArrayList5.get(0);
	if(listNode7 != null)
	{
	  listNode8.addAll(listNode7);
	}
        }

        pstoryNode1 = new AStory(ptitleNode2, ppackageNode3, proleNode4, null, pbenefitNode6, listNode8);
        }
	nodeList.add(pstoryNode1);
        return nodeList;
    }



    ArrayList new28() /* reduce AAstory29Story */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStory pstoryNode1;
        {
        PTitle ptitleNode2;
        Object nullNode3 = null;
        Object nullNode4 = null;
        PFeature pfeatureNode5;
        PBenefit pbenefitNode6;
        TypedLinkedList listNode8 = new TypedLinkedList();
        ptitleNode2 = (PTitle)nodeArrayList1.get(0);
        pfeatureNode5 = (PFeature)nodeArrayList2.get(0);
        pbenefitNode6 = (PBenefit)nodeArrayList3.get(0);
        {
        TypedLinkedList listNode7 = new TypedLinkedList();
        listNode7 = (TypedLinkedList)nodeArrayList4.get(0);
	if(listNode7 != null)
	{
	  listNode8.addAll(listNode7);
	}
        }

        pstoryNode1 = new AStory(ptitleNode2, null, null, pfeatureNode5, pbenefitNode6, listNode8);
        }
	nodeList.add(pstoryNode1);
        return nodeList;
    }



    ArrayList new29() /* reduce AAstory30Story */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStory pstoryNode1;
        {
        PTitle ptitleNode2;
        PPackage ppackageNode3;
        Object nullNode4 = null;
        PFeature pfeatureNode5;
        PBenefit pbenefitNode6;
        TypedLinkedList listNode8 = new TypedLinkedList();
        ptitleNode2 = (PTitle)nodeArrayList1.get(0);
        ppackageNode3 = (PPackage)nodeArrayList2.get(0);
        pfeatureNode5 = (PFeature)nodeArrayList3.get(0);
        pbenefitNode6 = (PBenefit)nodeArrayList4.get(0);
        {
        TypedLinkedList listNode7 = new TypedLinkedList();
        listNode7 = (TypedLinkedList)nodeArrayList5.get(0);
	if(listNode7 != null)
	{
	  listNode8.addAll(listNode7);
	}
        }

        pstoryNode1 = new AStory(ptitleNode2, ppackageNode3, null, pfeatureNode5, pbenefitNode6, listNode8);
        }
	nodeList.add(pstoryNode1);
        return nodeList;
    }



    ArrayList new30() /* reduce AAstory31Story */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStory pstoryNode1;
        {
        PTitle ptitleNode2;
        Object nullNode3 = null;
        PRole proleNode4;
        PFeature pfeatureNode5;
        PBenefit pbenefitNode6;
        TypedLinkedList listNode8 = new TypedLinkedList();
        ptitleNode2 = (PTitle)nodeArrayList1.get(0);
        proleNode4 = (PRole)nodeArrayList2.get(0);
        pfeatureNode5 = (PFeature)nodeArrayList3.get(0);
        pbenefitNode6 = (PBenefit)nodeArrayList4.get(0);
        {
        TypedLinkedList listNode7 = new TypedLinkedList();
        listNode7 = (TypedLinkedList)nodeArrayList5.get(0);
	if(listNode7 != null)
	{
	  listNode8.addAll(listNode7);
	}
        }

        pstoryNode1 = new AStory(ptitleNode2, null, proleNode4, pfeatureNode5, pbenefitNode6, listNode8);
        }
	nodeList.add(pstoryNode1);
        return nodeList;
    }



    ArrayList new31() /* reduce AAstory32Story */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStory pstoryNode1;
        {
        PTitle ptitleNode2;
        PPackage ppackageNode3;
        PRole proleNode4;
        PFeature pfeatureNode5;
        PBenefit pbenefitNode6;
        TypedLinkedList listNode8 = new TypedLinkedList();
        ptitleNode2 = (PTitle)nodeArrayList1.get(0);
        ppackageNode3 = (PPackage)nodeArrayList2.get(0);
        proleNode4 = (PRole)nodeArrayList3.get(0);
        pfeatureNode5 = (PFeature)nodeArrayList4.get(0);
        pbenefitNode6 = (PBenefit)nodeArrayList5.get(0);
        {
        TypedLinkedList listNode7 = new TypedLinkedList();
        listNode7 = (TypedLinkedList)nodeArrayList6.get(0);
	if(listNode7 != null)
	{
	  listNode8.addAll(listNode7);
	}
        }

        pstoryNode1 = new AStory(ptitleNode2, ppackageNode3, proleNode4, pfeatureNode5, pbenefitNode6, listNode8);
        }
	nodeList.add(pstoryNode1);
        return nodeList;
    }



    ArrayList new32() /* reduce ATitle */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PTitle ptitleNode1;
        {
        TTitleKeyword ttitlekeywordNode2;
        TSpace tspaceNode3;
        PPhrase pphraseNode4;
        TEndl tendlNode5;
        ttitlekeywordNode2 = (TTitleKeyword)nodeArrayList1.get(0);
        tspaceNode3 = (TSpace)nodeArrayList2.get(0);
        pphraseNode4 = (PPhrase)nodeArrayList3.get(0);
        tendlNode5 = (TEndl)nodeArrayList4.get(0);

        ptitleNode1 = new ATitle(ttitlekeywordNode2, tspaceNode3, pphraseNode4, tendlNode5);
        }
	nodeList.add(ptitleNode1);
        return nodeList;
    }



    ArrayList new33() /* reduce APackage */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PPackage ppackageNode1;
        {
        TPackageKeyword tpackagekeywordNode2;
        TSpace tspaceNode3;
        TPackageName tpackagenameNode4;
        TEndl tendlNode5;
        tpackagekeywordNode2 = (TPackageKeyword)nodeArrayList1.get(0);
        tspaceNode3 = (TSpace)nodeArrayList2.get(0);
        tpackagenameNode4 = (TPackageName)nodeArrayList3.get(0);
        tendlNode5 = (TEndl)nodeArrayList4.get(0);

        ppackageNode1 = new APackage(tpackagekeywordNode2, tspaceNode3, tpackagenameNode4, tendlNode5);
        }
	nodeList.add(ppackageNode1);
        return nodeList;
    }



    ArrayList new34() /* reduce ARole */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PRole proleNode1;
        {
        TAsA tasaNode2;
        TSpace tspaceNode3;
        PPhrase pphraseNode4;
        TEndl tendlNode5;
        tasaNode2 = (TAsA)nodeArrayList1.get(0);
        tspaceNode3 = (TSpace)nodeArrayList2.get(0);
        pphraseNode4 = (PPhrase)nodeArrayList3.get(0);
        tendlNode5 = (TEndl)nodeArrayList4.get(0);

        proleNode1 = new ARole(tasaNode2, tspaceNode3, pphraseNode4, tendlNode5);
        }
	nodeList.add(proleNode1);
        return nodeList;
    }



    ArrayList new35() /* reduce AFeature */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PFeature pfeatureNode1;
        {
        TIWant tiwantNode2;
        TSpace tspaceNode3;
        PPhrase pphraseNode4;
        TEndl tendlNode5;
        tiwantNode2 = (TIWant)nodeArrayList1.get(0);
        tspaceNode3 = (TSpace)nodeArrayList2.get(0);
        pphraseNode4 = (PPhrase)nodeArrayList3.get(0);
        tendlNode5 = (TEndl)nodeArrayList4.get(0);

        pfeatureNode1 = new AFeature(tiwantNode2, tspaceNode3, pphraseNode4, tendlNode5);
        }
	nodeList.add(pfeatureNode1);
        return nodeList;
    }



    ArrayList new36() /* reduce ABenefit */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PBenefit pbenefitNode1;
        {
        TSoThat tsothatNode2;
        TSpace tspaceNode3;
        PPhrase pphraseNode4;
        TEndl tendlNode5;
        tsothatNode2 = (TSoThat)nodeArrayList1.get(0);
        tspaceNode3 = (TSpace)nodeArrayList2.get(0);
        pphraseNode4 = (PPhrase)nodeArrayList3.get(0);
        tendlNode5 = (TEndl)nodeArrayList4.get(0);

        pbenefitNode1 = new ABenefit(tsothatNode2, tspaceNode3, pphraseNode4, tendlNode5);
        }
	nodeList.add(pbenefitNode1);
        return nodeList;
    }



    ArrayList new37() /* reduce AAscenario1Scenario */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PScenario pscenarioNode1;
        {
        PScenarioTitle pscenariotitleNode2;
        TypedLinkedList listNode3 = new TypedLinkedList();
        Object nullNode4 = null;
        TypedLinkedList listNode5 = new TypedLinkedList();
        pscenariotitleNode2 = (PScenarioTitle)nodeArrayList1.get(0);
        {
        }
        {
        }

        pscenarioNode1 = new AScenario(pscenariotitleNode2, listNode3, null, listNode5);
        }
	nodeList.add(pscenarioNode1);
        return nodeList;
    }



    ArrayList new38() /* reduce AAscenario2Scenario */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PScenario pscenarioNode1;
        {
        PScenarioTitle pscenariotitleNode2;
        TypedLinkedList listNode4 = new TypedLinkedList();
        Object nullNode5 = null;
        TypedLinkedList listNode6 = new TypedLinkedList();
        pscenariotitleNode2 = (PScenarioTitle)nodeArrayList1.get(0);
        {
        TypedLinkedList listNode3 = new TypedLinkedList();
        listNode3 = (TypedLinkedList)nodeArrayList2.get(0);
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }
        {
        }

        pscenarioNode1 = new AScenario(pscenariotitleNode2, listNode4, null, listNode6);
        }
	nodeList.add(pscenarioNode1);
        return nodeList;
    }



    ArrayList new39() /* reduce AAscenario3Scenario */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PScenario pscenarioNode1;
        {
        PScenarioTitle pscenariotitleNode2;
        TypedLinkedList listNode3 = new TypedLinkedList();
        PEvent peventNode4;
        TypedLinkedList listNode5 = new TypedLinkedList();
        pscenariotitleNode2 = (PScenarioTitle)nodeArrayList1.get(0);
        {
        }
        peventNode4 = (PEvent)nodeArrayList2.get(0);
        {
        }

        pscenarioNode1 = new AScenario(pscenariotitleNode2, listNode3, peventNode4, listNode5);
        }
	nodeList.add(pscenarioNode1);
        return nodeList;
    }



    ArrayList new40() /* reduce AAscenario4Scenario */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PScenario pscenarioNode1;
        {
        PScenarioTitle pscenariotitleNode2;
        TypedLinkedList listNode4 = new TypedLinkedList();
        PEvent peventNode5;
        TypedLinkedList listNode6 = new TypedLinkedList();
        pscenariotitleNode2 = (PScenarioTitle)nodeArrayList1.get(0);
        {
        TypedLinkedList listNode3 = new TypedLinkedList();
        listNode3 = (TypedLinkedList)nodeArrayList2.get(0);
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }
        peventNode5 = (PEvent)nodeArrayList3.get(0);
        {
        }

        pscenarioNode1 = new AScenario(pscenariotitleNode2, listNode4, peventNode5, listNode6);
        }
	nodeList.add(pscenarioNode1);
        return nodeList;
    }



    ArrayList new41() /* reduce AAscenario5Scenario */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PScenario pscenarioNode1;
        {
        PScenarioTitle pscenariotitleNode2;
        TypedLinkedList listNode3 = new TypedLinkedList();
        Object nullNode4 = null;
        TypedLinkedList listNode6 = new TypedLinkedList();
        pscenariotitleNode2 = (PScenarioTitle)nodeArrayList1.get(0);
        {
        }
        {
        TypedLinkedList listNode5 = new TypedLinkedList();
        listNode5 = (TypedLinkedList)nodeArrayList2.get(0);
	if(listNode5 != null)
	{
	  listNode6.addAll(listNode5);
	}
        }

        pscenarioNode1 = new AScenario(pscenariotitleNode2, listNode3, null, listNode6);
        }
	nodeList.add(pscenarioNode1);
        return nodeList;
    }



    ArrayList new42() /* reduce AAscenario6Scenario */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PScenario pscenarioNode1;
        {
        PScenarioTitle pscenariotitleNode2;
        TypedLinkedList listNode4 = new TypedLinkedList();
        Object nullNode5 = null;
        TypedLinkedList listNode7 = new TypedLinkedList();
        pscenariotitleNode2 = (PScenarioTitle)nodeArrayList1.get(0);
        {
        TypedLinkedList listNode3 = new TypedLinkedList();
        listNode3 = (TypedLinkedList)nodeArrayList2.get(0);
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }
        {
        TypedLinkedList listNode6 = new TypedLinkedList();
        listNode6 = (TypedLinkedList)nodeArrayList3.get(0);
	if(listNode6 != null)
	{
	  listNode7.addAll(listNode6);
	}
        }

        pscenarioNode1 = new AScenario(pscenariotitleNode2, listNode4, null, listNode7);
        }
	nodeList.add(pscenarioNode1);
        return nodeList;
    }



    ArrayList new43() /* reduce AAscenario7Scenario */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PScenario pscenarioNode1;
        {
        PScenarioTitle pscenariotitleNode2;
        TypedLinkedList listNode3 = new TypedLinkedList();
        PEvent peventNode4;
        TypedLinkedList listNode6 = new TypedLinkedList();
        pscenariotitleNode2 = (PScenarioTitle)nodeArrayList1.get(0);
        {
        }
        peventNode4 = (PEvent)nodeArrayList2.get(0);
        {
        TypedLinkedList listNode5 = new TypedLinkedList();
        listNode5 = (TypedLinkedList)nodeArrayList3.get(0);
	if(listNode5 != null)
	{
	  listNode6.addAll(listNode5);
	}
        }

        pscenarioNode1 = new AScenario(pscenariotitleNode2, listNode3, peventNode4, listNode6);
        }
	nodeList.add(pscenarioNode1);
        return nodeList;
    }



    ArrayList new44() /* reduce AAscenario8Scenario */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PScenario pscenarioNode1;
        {
        PScenarioTitle pscenariotitleNode2;
        TypedLinkedList listNode4 = new TypedLinkedList();
        PEvent peventNode5;
        TypedLinkedList listNode7 = new TypedLinkedList();
        pscenariotitleNode2 = (PScenarioTitle)nodeArrayList1.get(0);
        {
        TypedLinkedList listNode3 = new TypedLinkedList();
        listNode3 = (TypedLinkedList)nodeArrayList2.get(0);
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }
        peventNode5 = (PEvent)nodeArrayList3.get(0);
        {
        TypedLinkedList listNode6 = new TypedLinkedList();
        listNode6 = (TypedLinkedList)nodeArrayList4.get(0);
	if(listNode6 != null)
	{
	  listNode7.addAll(listNode6);
	}
        }

        pscenarioNode1 = new AScenario(pscenariotitleNode2, listNode4, peventNode5, listNode7);
        }
	nodeList.add(pscenarioNode1);
        return nodeList;
    }



    ArrayList new45() /* reduce AScenarioTitle */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PScenarioTitle pscenariotitleNode1;
        {
        TScenarioKeyword tscenariokeywordNode2;
        TSpace tspaceNode3;
        PPhrase pphraseNode4;
        TEndl tendlNode5;
        tscenariokeywordNode2 = (TScenarioKeyword)nodeArrayList1.get(0);
        tspaceNode3 = (TSpace)nodeArrayList2.get(0);
        pphraseNode4 = (PPhrase)nodeArrayList3.get(0);
        tendlNode5 = (TEndl)nodeArrayList4.get(0);

        pscenariotitleNode1 = new AScenarioTitle(tscenariokeywordNode2, tspaceNode3, pphraseNode4, tendlNode5);
        }
	nodeList.add(pscenariotitleNode1);
        return nodeList;
    }



    ArrayList new46() /* reduce AContext */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PContext pcontextNode1;
        {
        TGiven tgivenNode2;
        TSpace tspaceNode3;
        PPhrase pphraseNode4;
        TEndl tendlNode5;
        tgivenNode2 = (TGiven)nodeArrayList1.get(0);
        tspaceNode3 = (TSpace)nodeArrayList2.get(0);
        pphraseNode4 = (PPhrase)nodeArrayList3.get(0);
        tendlNode5 = (TEndl)nodeArrayList4.get(0);

        pcontextNode1 = new AContext(tgivenNode2, tspaceNode3, pphraseNode4, tendlNode5);
        }
	nodeList.add(pcontextNode1);
        return nodeList;
    }



    ArrayList new47() /* reduce AEvent */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PEvent peventNode1;
        {
        TWhen twhenNode2;
        TSpace tspaceNode3;
        PPhrase pphraseNode4;
        TEndl tendlNode5;
        twhenNode2 = (TWhen)nodeArrayList1.get(0);
        tspaceNode3 = (TSpace)nodeArrayList2.get(0);
        pphraseNode4 = (PPhrase)nodeArrayList3.get(0);
        tendlNode5 = (TEndl)nodeArrayList4.get(0);

        peventNode1 = new AEvent(twhenNode2, tspaceNode3, pphraseNode4, tendlNode5);
        }
	nodeList.add(peventNode1);
        return nodeList;
    }



    ArrayList new48() /* reduce AOutcome */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        POutcome poutcomeNode1;
        {
        TThen tthenNode2;
        TSpace tspaceNode3;
        PPhrase pphraseNode4;
        TEndl tendlNode5;
        tthenNode2 = (TThen)nodeArrayList1.get(0);
        tspaceNode3 = (TSpace)nodeArrayList2.get(0);
        pphraseNode4 = (PPhrase)nodeArrayList3.get(0);
        tendlNode5 = (TEndl)nodeArrayList4.get(0);

        poutcomeNode1 = new AOutcome(tthenNode2, tspaceNode3, pphraseNode4, tendlNode5);
        }
	nodeList.add(poutcomeNode1);
        return nodeList;
    }



    ArrayList new49() /* reduce APhrase */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PPhrase pphraseNode1;
        {
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        TypedLinkedList listNode2 = new TypedLinkedList();
        listNode2 = (TypedLinkedList)nodeArrayList1.get(0);
	if(listNode2 != null)
	{
	  listNode3.addAll(listNode2);
	}
        }

        pphraseNode1 = new APhrase(listNode3);
        }
	nodeList.add(pphraseNode1);
        return nodeList;
    }



    ArrayList new50() /* reduce AWordWordOrSpace */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PWordOrSpace pwordorspaceNode1;
        {
        TWord twordNode2;
        twordNode2 = (TWord)nodeArrayList1.get(0);

        pwordorspaceNode1 = new AWordWordOrSpace(twordNode2);
        }
	nodeList.add(pwordorspaceNode1);
        return nodeList;
    }



    ArrayList new51() /* reduce ASpaceWordOrSpace */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PWordOrSpace pwordorspaceNode1;
        {
        TSpace tspaceNode2;
        tspaceNode2 = (TSpace)nodeArrayList1.get(0);

        pwordorspaceNode1 = new ASpaceWordOrSpace(tspaceNode2);
        }
	nodeList.add(pwordorspaceNode1);
        return nodeList;
    }



    ArrayList new52() /* reduce ATerminal$Scenario */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode2 = new TypedLinkedList();
        {
        PScenario pscenarioNode1;
        pscenarioNode1 = (PScenario)nodeArrayList1.get(0);
	if(pscenarioNode1 != null)
	{
	  listNode2.add(pscenarioNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    ArrayList new53() /* reduce ANonTerminal$Scenario */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        TypedLinkedList listNode1 = new TypedLinkedList();
        PScenario pscenarioNode2;
        listNode1 = (TypedLinkedList)nodeArrayList1.get(0);
        pscenarioNode2 = (PScenario)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pscenarioNode2 != null)
	{
	  listNode3.add(pscenarioNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    ArrayList new54() /* reduce ATerminal$Context */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode2 = new TypedLinkedList();
        {
        PContext pcontextNode1;
        pcontextNode1 = (PContext)nodeArrayList1.get(0);
	if(pcontextNode1 != null)
	{
	  listNode2.add(pcontextNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    ArrayList new55() /* reduce ANonTerminal$Context */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        TypedLinkedList listNode1 = new TypedLinkedList();
        PContext pcontextNode2;
        listNode1 = (TypedLinkedList)nodeArrayList1.get(0);
        pcontextNode2 = (PContext)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pcontextNode2 != null)
	{
	  listNode3.add(pcontextNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    ArrayList new56() /* reduce ATerminal$Outcome */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode2 = new TypedLinkedList();
        {
        POutcome poutcomeNode1;
        poutcomeNode1 = (POutcome)nodeArrayList1.get(0);
	if(poutcomeNode1 != null)
	{
	  listNode2.add(poutcomeNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    ArrayList new57() /* reduce ANonTerminal$Outcome */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        TypedLinkedList listNode1 = new TypedLinkedList();
        POutcome poutcomeNode2;
        listNode1 = (TypedLinkedList)nodeArrayList1.get(0);
        poutcomeNode2 = (POutcome)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(poutcomeNode2 != null)
	{
	  listNode3.add(poutcomeNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    ArrayList new58() /* reduce ATerminal$WordOrSpace */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode2 = new TypedLinkedList();
        {
        PWordOrSpace pwordorspaceNode1;
        pwordorspaceNode1 = (PWordOrSpace)nodeArrayList1.get(0);
	if(pwordorspaceNode1 != null)
	{
	  listNode2.add(pwordorspaceNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    ArrayList new59() /* reduce ANonTerminal$WordOrSpace */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        TypedLinkedList listNode1 = new TypedLinkedList();
        PWordOrSpace pwordorspaceNode2;
        listNode1 = (TypedLinkedList)nodeArrayList1.get(0);
        pwordorspaceNode2 = (PWordOrSpace)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pwordorspaceNode2 != null)
	{
	  listNode3.add(pwordorspaceNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    private static int[][][] actionTable;
/*      {
			{{-1, ERROR, 0}, {0, SHIFT, 1}, },
			{{-1, ERROR, 1}, {9, SHIFT, 4}, },
			{{-1, ERROR, 2}, {13, ACCEPT, -1}, },
			{{-1, REDUCE, 0}, {1, SHIFT, 5}, {2, SHIFT, 6}, {3, SHIFT, 7}, {4, SHIFT, 8}, {5, SHIFT, 9}, },
			{{-1, ERROR, 4}, {9, SHIFT, 17}, {10, SHIFT, 18}, },
			{{-1, ERROR, 5}, {9, SHIFT, 22}, },
			{{-1, ERROR, 6}, {9, SHIFT, 23}, },
			{{-1, ERROR, 7}, {9, SHIFT, 24}, },
			{{-1, ERROR, 8}, {9, SHIFT, 25}, },
			{{-1, ERROR, 9}, {9, SHIFT, 26}, },
			{{-1, REDUCE, 1}, {2, SHIFT, 6}, {3, SHIFT, 7}, {4, SHIFT, 8}, {5, SHIFT, 9}, },
			{{-1, REDUCE, 2}, {2, SHIFT, 6}, {4, SHIFT, 8}, {5, SHIFT, 9}, },
			{{-1, REDUCE, 4}, {2, SHIFT, 6}, {5, SHIFT, 9}, },
			{{-1, REDUCE, 8}, {2, SHIFT, 6}, },
			{{-1, REDUCE, 52}, },
			{{-1, REDUCE, 37}, {6, SHIFT, 37}, {7, SHIFT, 38}, {8, SHIFT, 39}, },
			{{-1, REDUCE, 16}, {2, SHIFT, 6}, },
			{{-1, REDUCE, 51}, },
			{{-1, REDUCE, 50}, },
			{{-1, ERROR, 19}, {12, SHIFT, 46}, },
			{{-1, REDUCE, 58}, },
			{{-1, REDUCE, 49}, {9, SHIFT, 17}, {10, SHIFT, 18}, },
			{{-1, ERROR, 22}, {11, SHIFT, 48}, },
			{{-1, ERROR, 23}, {9, SHIFT, 17}, {10, SHIFT, 18}, },
			{{-1, ERROR, 24}, {9, SHIFT, 17}, {10, SHIFT, 18}, },
			{{-1, ERROR, 25}, {9, SHIFT, 17}, {10, SHIFT, 18}, },
			{{-1, ERROR, 26}, {9, SHIFT, 17}, {10, SHIFT, 18}, },
			{{-1, REDUCE, 3}, {2, SHIFT, 6}, {4, SHIFT, 8}, {5, SHIFT, 9}, },
			{{-1, REDUCE, 5}, {2, SHIFT, 6}, {5, SHIFT, 9}, },
			{{-1, REDUCE, 9}, {2, SHIFT, 6}, },
			{{-1, REDUCE, 17}, {2, SHIFT, 6}, },
			{{-1, REDUCE, 6}, {2, SHIFT, 6}, {5, SHIFT, 9}, },
			{{-1, REDUCE, 10}, {2, SHIFT, 6}, },
			{{-1, REDUCE, 18}, {2, SHIFT, 6}, },
			{{-1, REDUCE, 12}, {2, SHIFT, 6}, },
			{{-1, REDUCE, 20}, {2, SHIFT, 6}, },
			{{-1, REDUCE, 24}, {2, SHIFT, 6}, },
			{{-1, ERROR, 37}, {9, SHIFT, 63}, },
			{{-1, ERROR, 38}, {9, SHIFT, 64}, },
			{{-1, ERROR, 39}, {9, SHIFT, 65}, },
			{{-1, REDUCE, 54}, },
			{{-1, REDUCE, 39}, {8, SHIFT, 39}, },
			{{-1, REDUCE, 56}, },
			{{-1, REDUCE, 38}, {6, SHIFT, 37}, {7, SHIFT, 38}, {8, SHIFT, 39}, },
			{{-1, REDUCE, 41}, {8, SHIFT, 39}, },
			{{-1, REDUCE, 53}, },
			{{-1, REDUCE, 32}, },
			{{-1, REDUCE, 59}, },
			{{-1, ERROR, 48}, {12, SHIFT, 71}, },
			{{-1, ERROR, 49}, {12, SHIFT, 72}, },
			{{-1, ERROR, 50}, {12, SHIFT, 73}, },
			{{-1, ERROR, 51}, {12, SHIFT, 74}, },
			{{-1, ERROR, 52}, {12, SHIFT, 75}, },
			{{-1, REDUCE, 7}, {2, SHIFT, 6}, {5, SHIFT, 9}, },
			{{-1, REDUCE, 11}, {2, SHIFT, 6}, },
			{{-1, REDUCE, 19}, {2, SHIFT, 6}, },
			{{-1, REDUCE, 13}, {2, SHIFT, 6}, },
			{{-1, REDUCE, 21}, {2, SHIFT, 6}, },
			{{-1, REDUCE, 25}, {2, SHIFT, 6}, },
			{{-1, REDUCE, 14}, {2, SHIFT, 6}, },
			{{-1, REDUCE, 22}, {2, SHIFT, 6}, },
			{{-1, REDUCE, 26}, {2, SHIFT, 6}, },
			{{-1, REDUCE, 28}, {2, SHIFT, 6}, },
			{{-1, ERROR, 63}, {9, SHIFT, 17}, {10, SHIFT, 18}, },
			{{-1, ERROR, 64}, {9, SHIFT, 17}, {10, SHIFT, 18}, },
			{{-1, ERROR, 65}, {9, SHIFT, 17}, {10, SHIFT, 18}, },
			{{-1, REDUCE, 43}, {8, SHIFT, 39}, },
			{{-1, REDUCE, 55}, },
			{{-1, REDUCE, 40}, {8, SHIFT, 39}, },
			{{-1, REDUCE, 42}, {8, SHIFT, 39}, },
			{{-1, REDUCE, 57}, },
			{{-1, REDUCE, 33}, },
			{{-1, REDUCE, 45}, },
			{{-1, REDUCE, 34}, },
			{{-1, REDUCE, 35}, },
			{{-1, REDUCE, 36}, },
			{{-1, REDUCE, 15}, {2, SHIFT, 6}, },
			{{-1, REDUCE, 23}, {2, SHIFT, 6}, },
			{{-1, REDUCE, 27}, {2, SHIFT, 6}, },
			{{-1, REDUCE, 29}, {2, SHIFT, 6}, },
			{{-1, REDUCE, 30}, {2, SHIFT, 6}, },
			{{-1, ERROR, 81}, {12, SHIFT, 86}, },
			{{-1, ERROR, 82}, {12, SHIFT, 87}, },
			{{-1, ERROR, 83}, {12, SHIFT, 88}, },
			{{-1, REDUCE, 44}, {8, SHIFT, 39}, },
			{{-1, REDUCE, 31}, {2, SHIFT, 6}, },
			{{-1, REDUCE, 46}, },
			{{-1, REDUCE, 47}, },
			{{-1, REDUCE, 48}, },
        };*/
    private static int[][][] gotoTable;
/*      {
			{{-1, 2}, },
			{{-1, 3}, },
			{{-1, 10}, },
			{{-1, 11}, {10, 27}, },
			{{-1, 12}, {10, 28}, {11, 31}, {27, 53}, },
			{{-1, 13}, {10, 29}, {11, 32}, {12, 34}, {27, 54}, {28, 56}, {31, 59}, {53, 76}, },
			{{-1, 14}, {16, 45}, {30, 45}, {33, 45}, {35, 45}, {36, 45}, {55, 45}, {57, 45}, {58, 45}, {60, 45}, {61, 45}, {62, 45}, {77, 45}, {78, 45}, {79, 45}, {80, 45}, {85, 45}, },
			{{-1, 15}, },
			{{-1, 40}, {43, 67}, },
			{{-1, 41}, {43, 68}, },
			{{-1, 42}, {44, 70}, {66, 70}, {69, 70}, {84, 70}, },
			{{-1, 19}, {23, 49}, {24, 50}, {25, 51}, {26, 52}, {63, 81}, {64, 82}, {65, 83}, },
			{{-1, 20}, {21, 47}, },
			{{-1, 16}, {10, 30}, {11, 33}, {12, 35}, {13, 36}, {27, 55}, {28, 57}, {29, 58}, {31, 60}, {32, 61}, {34, 62}, {53, 77}, {54, 78}, {56, 79}, {59, 80}, {76, 85}, },
			{{-1, 43}, },
			{{-1, 44}, {41, 66}, {43, 69}, {68, 84}, },
			{{-1, 21}, },
        };*/
    private static String[] errorMessages;
/*      {
			"expecting: 'Title:'",
			"expecting: space",
			"expecting: EOF",
			"expecting: 'Package:', 'Scenario:', 'As a', 'I want', 'So that', EOF",
			"expecting: space, word",
			"expecting: 'Scenario:', 'As a', 'I want', 'So that', EOF",
			"expecting: 'Scenario:', 'I want', 'So that', EOF",
			"expecting: 'Scenario:', 'So that', EOF",
			"expecting: 'Scenario:', EOF",
			"expecting: 'Scenario:', 'Given', 'When', 'Then', EOF",
			"expecting: space, word, endl",
			"expecting: endl",
			"expecting: package name",
			"expecting: 'Scenario:', 'Then', EOF",
        };*/
    private static int[] errors;
/*      {
			0, 1, 2, 3, 4, 1, 1, 1, 1, 1, 5, 6, 7, 8, 8, 9, 8, 10, 10, 11, 10, 10, 12, 4, 4, 4, 4, 6, 7, 8, 8, 7, 8, 8, 8, 8, 8, 1, 1, 1, 9, 13, 13, 9, 13, 8, 3, 10, 11, 11, 11, 11, 11, 7, 8, 8, 8, 8, 8, 8, 8, 8, 8, 4, 4, 4, 13, 9, 13, 13, 13, 5, 9, 6, 7, 8, 8, 8, 8, 8, 8, 11, 11, 11, 13, 8, 9, 13, 13, 
        };*/

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Parser.class.getResourceAsStream("parser.dat")));

            // read actionTable
            int length = s.readInt();
            actionTable = new int[length][][];
            for(int i = 0; i < actionTable.length; i++)
            {
                length = s.readInt();
                actionTable[i] = new int[length][3];
                for(int j = 0; j < actionTable[i].length; j++)
                {
                for(int k = 0; k < 3; k++)
                {
                    actionTable[i][j][k] = s.readInt();
                }
                }
            }

            // read gotoTable
            length = s.readInt();
            gotoTable = new int[length][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][2];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                for(int k = 0; k < 2; k++)
                {
                    gotoTable[i][j][k] = s.readInt();
                }
                }
            }

            // read errorMessages
            length = s.readInt();
            errorMessages = new String[length];
            for(int i = 0; i < errorMessages.length; i++)
            {
                length = s.readInt();
                StringBuffer buffer = new StringBuffer();

                for(int j = 0; j < length; j++)
                {
                buffer.append(s.readChar());
                }
                errorMessages[i] = buffer.toString();
            }

            // read errors
            length = s.readInt();
            errors = new int[length];
            for(int i = 0; i < errors.length; i++)
            {
                errors[i] = s.readInt();
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"parser.dat\" is either missing or corrupted.");
        }
    }
}
