/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.thoughtworks.jbehave.story.codegen.sablecc.node;

import com.thoughtworks.jbehave.story.codegen.sablecc.analysis.*;

public final class TScenarioKeyword extends Token
{
    public TScenarioKeyword()
    {
        super.setText("Scenario:");
    }

    public TScenarioKeyword(int line, int pos)
    {
        super.setText("Scenario:");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TScenarioKeyword(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTScenarioKeyword(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TScenarioKeyword text.");
    }
}
