/* This file was generated by SableCC (http://www.sablecc.org/). */

package jbehave.core.story.codegen.sablecc.node;

import jbehave.core.story.codegen.sablecc.analysis.Analysis;

public final class TTitleKeyword extends Token
{
    public TTitleKeyword()
    {
        super.setText("Title:");
    }

    public TTitleKeyword(int line, int pos)
    {
        super.setText("Title:");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TTitleKeyword(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTitleKeyword(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TTitleKeyword text.");
    }
}
