package org.jbehave.scenario.reporters;

import java.io.File;
import java.util.List;

/**
 * A report renderer is responsible for creating a collective view of file-based
 * outputs generated by the reporters. The renderer assumes all reports have
 * been generated to a give output directory with the given formats. 
 */
public interface ReportRenderer {

    void render(File outputDirectory, List<String> formats);

}
