package org.jbehave.scenario.reporters;

import java.io.File;

/**
 * A report renderer is responsible for creating a collective view of file-based
 * outputs generated by the reporters. The renderer assumes all reports have
 * been generated to a give output directory and that a rendering format will be
 * provided.
 */
public interface ReportRenderer {

    void render(File outputDirectory, String format);

}
