Story: the player makes a line

As a game player
I want lines to disappear when I complete them
So that I can progress the game

Scenario: the player drops the glyph to make a line

Given the junk has a hole and a glyph of the right shape is above it
When the player presses the drop key
and time passes
Then the line should disappear and the next glyph should appear
..ZZ...
...ZZ..
.......
.......
.......
.......
.......
.......
.......
.......
...X...
...XX.X
.XXXX.X

