/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.thoughtworks.jbehave.story.codegen.sablecc.parser;

import com.thoughtworks.jbehave.story.codegen.sablecc.analysis.*;
import com.thoughtworks.jbehave.story.codegen.sablecc.lexer.*;
import com.thoughtworks.jbehave.story.codegen.sablecc.node.*;

import java.util.*;

import java.io.DataInputStream;
import java.io.BufferedInputStream;
import java.io.IOException;

public class Parser
{
    public final Analysis ignoredTokens = new AnalysisAdapter();

    protected ArrayList nodeList;

    private final Lexer lexer;
    private final ListIterator stack = new LinkedList().listIterator();
    private int last_shift;
    private int last_pos;
    private int last_line;
    private Token last_token;
    private final TokenIndex converter = new TokenIndex();
    private final int[] action = new int[2];

    private final static int SHIFT = 0;
    private final static int REDUCE = 1;
    private final static int ACCEPT = 2;
    private final static int ERROR = 3;

    public Parser(Lexer lexer)
    {
        this.lexer = lexer;
    }

    protected void filter() throws ParserException, LexerException, IOException
    {
    }

    private void push(int numstate, ArrayList listNode, boolean hidden) throws ParserException, LexerException, IOException
    {
	this.nodeList = listNode;

        if(!hidden)
        {
            filter();
        }

        if(!stack.hasNext())
        {
            stack.add(new State(numstate, this.nodeList));
            return;
        }

        State s = (State) stack.next();
        s.state = numstate;
        s.nodes = this.nodeList;
    }

    private int goTo(int index)
    {
        int state = state();
        int low = 1;
        int high = gotoTable[index].length - 1;
        int value = gotoTable[index][0][1];

        while(low <= high)
        {
            int middle = (low + high) / 2;

            if(state < gotoTable[index][middle][0])
            {
                high = middle - 1;
            }
            else if(state > gotoTable[index][middle][0])
            {
                low = middle + 1;
            }
            else
            {
                value = gotoTable[index][middle][1];
                break;
            }
        }

        return value;
    }

    private int state()
    {
        State s = (State) stack.previous();
        stack.next();
        return s.state;
    }

    private ArrayList pop()
    {
        return (ArrayList) ((State) stack.previous()).nodes;
    }

    private int index(Switchable token)
    {
        converter.index = -1;
        token.apply(converter);
        return converter.index;
    }

    public Start parse() throws ParserException, LexerException, IOException
    {
        push(0, null, true);
        List ign = null;
        while(true)
        {
            while(index(lexer.peek()) == -1)
            {
                if(ign == null)
                {
                    ign = new TypedLinkedList(NodeCast.instance);
                }

                ign.add(lexer.next());
            }

            if(ign != null)
            {
                ignoredTokens.setIn(lexer.peek(), ign);
                ign = null;
            }

            last_pos = lexer.peek().getPos();
            last_line = lexer.peek().getLine();
            last_token = lexer.peek();

            int index = index(lexer.peek());
            action[0] = actionTable[state()][0][1];
            action[1] = actionTable[state()][0][2];

            int low = 1;
            int high = actionTable[state()].length - 1;

            while(low <= high)
            {
                int middle = (low + high) / 2;

                if(index < actionTable[state()][middle][0])
                {
                    high = middle - 1;
                }
                else if(index > actionTable[state()][middle][0])
                {
                    low = middle + 1;
                }
                else
                {
                    action[0] = actionTable[state()][middle][1];
                    action[1] = actionTable[state()][middle][2];
                    break;
                }
            }

            switch(action[0])
            {
                case SHIFT:
		    {
		        ArrayList list = new ArrayList();
		        list.add(lexer.next());
                        push(action[1], list, false);
                        last_shift = action[1];
                    }
		    break;
                case REDUCE:
                    switch(action[1])
                    {
                    case 0: /* reduce AAstory1Story */
		    {
			ArrayList list = new0();
			push(goTo(0), list, false);
		    }
		    break;
                    case 1: /* reduce AAstory2Story */
		    {
			ArrayList list = new1();
			push(goTo(0), list, false);
		    }
		    break;
                    case 2: /* reduce AAstory3Story */
		    {
			ArrayList list = new2();
			push(goTo(0), list, false);
		    }
		    break;
                    case 3: /* reduce AAstory4Story */
		    {
			ArrayList list = new3();
			push(goTo(0), list, false);
		    }
		    break;
                    case 4: /* reduce AAstory5Story */
		    {
			ArrayList list = new4();
			push(goTo(0), list, false);
		    }
		    break;
                    case 5: /* reduce AAstory6Story */
		    {
			ArrayList list = new5();
			push(goTo(0), list, false);
		    }
		    break;
                    case 6: /* reduce AAstory7Story */
		    {
			ArrayList list = new6();
			push(goTo(0), list, false);
		    }
		    break;
                    case 7: /* reduce AAstory8Story */
		    {
			ArrayList list = new7();
			push(goTo(0), list, false);
		    }
		    break;
                    case 8: /* reduce ATitle */
		    {
			ArrayList list = new8();
			push(goTo(1), list, false);
		    }
		    break;
                    case 9: /* reduce ARole */
		    {
			ArrayList list = new9();
			push(goTo(2), list, false);
		    }
		    break;
                    case 10: /* reduce AFeature */
		    {
			ArrayList list = new10();
			push(goTo(3), list, false);
		    }
		    break;
                    case 11: /* reduce ABenefit */
		    {
			ArrayList list = new11();
			push(goTo(4), list, false);
		    }
		    break;
                    case 12: /* reduce APhrase */
		    {
			ArrayList list = new12();
			push(goTo(5), list, false);
		    }
		    break;
                    case 13: /* reduce AWordWordOrSpace */
		    {
			ArrayList list = new13();
			push(goTo(6), list, false);
		    }
		    break;
                    case 14: /* reduce ASpaceWordOrSpace */
		    {
			ArrayList list = new14();
			push(goTo(6), list, false);
		    }
		    break;
                    case 15: /* reduce ATerminal$WordOrSpace */
		    {
			ArrayList list = new15();
			push(goTo(7), list, true);
		    }
		    break;
                    case 16: /* reduce ANonTerminal$WordOrSpace */
		    {
			ArrayList list = new16();
			push(goTo(7), list, true);
		    }
		    break;
                    }
                    break;
                case ACCEPT:
                    {
                        EOF node2 = (EOF) lexer.next();
                        PStory node1 = (PStory) ((ArrayList)pop()).get(0);
                        Start node = new Start(node1, node2);
                        return node;
                    }
                case ERROR:
                    throw new ParserException(last_token,
                        "[" + last_line + "," + last_pos + "] " +
                        errorMessages[errors[action[1]]]);
            }
        }
    }



    ArrayList new0() /* reduce AAstory1Story */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStory pstoryNode1;
        {
        PTitle ptitleNode2;
        Object nullNode3 = null;
        Object nullNode4 = null;
        Object nullNode5 = null;
        ptitleNode2 = (PTitle)nodeArrayList1.get(0);

        pstoryNode1 = new AStory(ptitleNode2, null, null, null);
        }
	nodeList.add(pstoryNode1);
        return nodeList;
    }



    ArrayList new1() /* reduce AAstory2Story */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStory pstoryNode1;
        {
        PTitle ptitleNode2;
        PRole proleNode3;
        Object nullNode4 = null;
        Object nullNode5 = null;
        ptitleNode2 = (PTitle)nodeArrayList1.get(0);
        proleNode3 = (PRole)nodeArrayList2.get(0);

        pstoryNode1 = new AStory(ptitleNode2, proleNode3, null, null);
        }
	nodeList.add(pstoryNode1);
        return nodeList;
    }



    ArrayList new2() /* reduce AAstory3Story */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStory pstoryNode1;
        {
        PTitle ptitleNode2;
        Object nullNode3 = null;
        PFeature pfeatureNode4;
        Object nullNode5 = null;
        ptitleNode2 = (PTitle)nodeArrayList1.get(0);
        pfeatureNode4 = (PFeature)nodeArrayList2.get(0);

        pstoryNode1 = new AStory(ptitleNode2, null, pfeatureNode4, null);
        }
	nodeList.add(pstoryNode1);
        return nodeList;
    }



    ArrayList new3() /* reduce AAstory4Story */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStory pstoryNode1;
        {
        PTitle ptitleNode2;
        PRole proleNode3;
        PFeature pfeatureNode4;
        Object nullNode5 = null;
        ptitleNode2 = (PTitle)nodeArrayList1.get(0);
        proleNode3 = (PRole)nodeArrayList2.get(0);
        pfeatureNode4 = (PFeature)nodeArrayList3.get(0);

        pstoryNode1 = new AStory(ptitleNode2, proleNode3, pfeatureNode4, null);
        }
	nodeList.add(pstoryNode1);
        return nodeList;
    }



    ArrayList new4() /* reduce AAstory5Story */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStory pstoryNode1;
        {
        PTitle ptitleNode2;
        Object nullNode3 = null;
        Object nullNode4 = null;
        PBenefit pbenefitNode5;
        ptitleNode2 = (PTitle)nodeArrayList1.get(0);
        pbenefitNode5 = (PBenefit)nodeArrayList2.get(0);

        pstoryNode1 = new AStory(ptitleNode2, null, null, pbenefitNode5);
        }
	nodeList.add(pstoryNode1);
        return nodeList;
    }



    ArrayList new5() /* reduce AAstory6Story */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStory pstoryNode1;
        {
        PTitle ptitleNode2;
        PRole proleNode3;
        Object nullNode4 = null;
        PBenefit pbenefitNode5;
        ptitleNode2 = (PTitle)nodeArrayList1.get(0);
        proleNode3 = (PRole)nodeArrayList2.get(0);
        pbenefitNode5 = (PBenefit)nodeArrayList3.get(0);

        pstoryNode1 = new AStory(ptitleNode2, proleNode3, null, pbenefitNode5);
        }
	nodeList.add(pstoryNode1);
        return nodeList;
    }



    ArrayList new6() /* reduce AAstory7Story */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStory pstoryNode1;
        {
        PTitle ptitleNode2;
        Object nullNode3 = null;
        PFeature pfeatureNode4;
        PBenefit pbenefitNode5;
        ptitleNode2 = (PTitle)nodeArrayList1.get(0);
        pfeatureNode4 = (PFeature)nodeArrayList2.get(0);
        pbenefitNode5 = (PBenefit)nodeArrayList3.get(0);

        pstoryNode1 = new AStory(ptitleNode2, null, pfeatureNode4, pbenefitNode5);
        }
	nodeList.add(pstoryNode1);
        return nodeList;
    }



    ArrayList new7() /* reduce AAstory8Story */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStory pstoryNode1;
        {
        PTitle ptitleNode2;
        PRole proleNode3;
        PFeature pfeatureNode4;
        PBenefit pbenefitNode5;
        ptitleNode2 = (PTitle)nodeArrayList1.get(0);
        proleNode3 = (PRole)nodeArrayList2.get(0);
        pfeatureNode4 = (PFeature)nodeArrayList3.get(0);
        pbenefitNode5 = (PBenefit)nodeArrayList4.get(0);

        pstoryNode1 = new AStory(ptitleNode2, proleNode3, pfeatureNode4, pbenefitNode5);
        }
	nodeList.add(pstoryNode1);
        return nodeList;
    }



    ArrayList new8() /* reduce ATitle */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PTitle ptitleNode1;
        {
        TTitleKeyword ttitlekeywordNode2;
        TSpace tspaceNode3;
        PPhrase pphraseNode4;
        TEndl tendlNode5;
        ttitlekeywordNode2 = (TTitleKeyword)nodeArrayList1.get(0);
        tspaceNode3 = (TSpace)nodeArrayList2.get(0);
        pphraseNode4 = (PPhrase)nodeArrayList3.get(0);
        tendlNode5 = (TEndl)nodeArrayList4.get(0);

        ptitleNode1 = new ATitle(ttitlekeywordNode2, tspaceNode3, pphraseNode4, tendlNode5);
        }
	nodeList.add(ptitleNode1);
        return nodeList;
    }



    ArrayList new9() /* reduce ARole */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PRole proleNode1;
        {
        TAsA tasaNode2;
        TSpace tspaceNode3;
        PPhrase pphraseNode4;
        TEndl tendlNode5;
        tasaNode2 = (TAsA)nodeArrayList1.get(0);
        tspaceNode3 = (TSpace)nodeArrayList2.get(0);
        pphraseNode4 = (PPhrase)nodeArrayList3.get(0);
        tendlNode5 = (TEndl)nodeArrayList4.get(0);

        proleNode1 = new ARole(tasaNode2, tspaceNode3, pphraseNode4, tendlNode5);
        }
	nodeList.add(proleNode1);
        return nodeList;
    }



    ArrayList new10() /* reduce AFeature */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PFeature pfeatureNode1;
        {
        TIWant tiwantNode2;
        TSpace tspaceNode3;
        PPhrase pphraseNode4;
        TEndl tendlNode5;
        tiwantNode2 = (TIWant)nodeArrayList1.get(0);
        tspaceNode3 = (TSpace)nodeArrayList2.get(0);
        pphraseNode4 = (PPhrase)nodeArrayList3.get(0);
        tendlNode5 = (TEndl)nodeArrayList4.get(0);

        pfeatureNode1 = new AFeature(tiwantNode2, tspaceNode3, pphraseNode4, tendlNode5);
        }
	nodeList.add(pfeatureNode1);
        return nodeList;
    }



    ArrayList new11() /* reduce ABenefit */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PBenefit pbenefitNode1;
        {
        TSoThat tsothatNode2;
        TSpace tspaceNode3;
        PPhrase pphraseNode4;
        TEndl tendlNode5;
        tsothatNode2 = (TSoThat)nodeArrayList1.get(0);
        tspaceNode3 = (TSpace)nodeArrayList2.get(0);
        pphraseNode4 = (PPhrase)nodeArrayList3.get(0);
        tendlNode5 = (TEndl)nodeArrayList4.get(0);

        pbenefitNode1 = new ABenefit(tsothatNode2, tspaceNode3, pphraseNode4, tendlNode5);
        }
	nodeList.add(pbenefitNode1);
        return nodeList;
    }



    ArrayList new12() /* reduce APhrase */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PPhrase pphraseNode1;
        {
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        TypedLinkedList listNode2 = new TypedLinkedList();
        listNode2 = (TypedLinkedList)nodeArrayList1.get(0);
	if(listNode2 != null)
	{
	  listNode3.addAll(listNode2);
	}
        }

        pphraseNode1 = new APhrase(listNode3);
        }
	nodeList.add(pphraseNode1);
        return nodeList;
    }



    ArrayList new13() /* reduce AWordWordOrSpace */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PWordOrSpace pwordorspaceNode1;
        {
        TWord twordNode2;
        twordNode2 = (TWord)nodeArrayList1.get(0);

        pwordorspaceNode1 = new AWordWordOrSpace(twordNode2);
        }
	nodeList.add(pwordorspaceNode1);
        return nodeList;
    }



    ArrayList new14() /* reduce ASpaceWordOrSpace */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PWordOrSpace pwordorspaceNode1;
        {
        TSpace tspaceNode2;
        tspaceNode2 = (TSpace)nodeArrayList1.get(0);

        pwordorspaceNode1 = new ASpaceWordOrSpace(tspaceNode2);
        }
	nodeList.add(pwordorspaceNode1);
        return nodeList;
    }



    ArrayList new15() /* reduce ATerminal$WordOrSpace */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode2 = new TypedLinkedList();
        {
        PWordOrSpace pwordorspaceNode1;
        pwordorspaceNode1 = (PWordOrSpace)nodeArrayList1.get(0);
	if(pwordorspaceNode1 != null)
	{
	  listNode2.add(pwordorspaceNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    ArrayList new16() /* reduce ANonTerminal$WordOrSpace */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        TypedLinkedList listNode1 = new TypedLinkedList();
        PWordOrSpace pwordorspaceNode2;
        listNode1 = (TypedLinkedList)nodeArrayList1.get(0);
        pwordorspaceNode2 = (PWordOrSpace)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pwordorspaceNode2 != null)
	{
	  listNode3.add(pwordorspaceNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    private static int[][][] actionTable;
/*      {
			{{-1, ERROR, 0}, {0, SHIFT, 1}, },
			{{-1, ERROR, 1}, {4, SHIFT, 4}, },
			{{-1, ERROR, 2}, {7, ACCEPT, -1}, },
			{{-1, REDUCE, 0}, {1, SHIFT, 5}, {2, SHIFT, 6}, {3, SHIFT, 7}, },
			{{-1, ERROR, 4}, {4, SHIFT, 11}, {5, SHIFT, 12}, },
			{{-1, ERROR, 5}, {4, SHIFT, 16}, },
			{{-1, ERROR, 6}, {4, SHIFT, 17}, },
			{{-1, ERROR, 7}, {4, SHIFT, 18}, },
			{{-1, REDUCE, 1}, {2, SHIFT, 6}, {3, SHIFT, 7}, },
			{{-1, REDUCE, 2}, {3, SHIFT, 7}, },
			{{-1, REDUCE, 4}, },
			{{-1, REDUCE, 14}, },
			{{-1, REDUCE, 13}, },
			{{-1, ERROR, 13}, {6, SHIFT, 22}, },
			{{-1, REDUCE, 15}, },
			{{-1, REDUCE, 12}, {4, SHIFT, 11}, {5, SHIFT, 12}, },
			{{-1, ERROR, 16}, {4, SHIFT, 11}, {5, SHIFT, 12}, },
			{{-1, ERROR, 17}, {4, SHIFT, 11}, {5, SHIFT, 12}, },
			{{-1, ERROR, 18}, {4, SHIFT, 11}, {5, SHIFT, 12}, },
			{{-1, REDUCE, 3}, {3, SHIFT, 7}, },
			{{-1, REDUCE, 5}, },
			{{-1, REDUCE, 6}, },
			{{-1, REDUCE, 8}, },
			{{-1, REDUCE, 16}, },
			{{-1, ERROR, 24}, {6, SHIFT, 28}, },
			{{-1, ERROR, 25}, {6, SHIFT, 29}, },
			{{-1, ERROR, 26}, {6, SHIFT, 30}, },
			{{-1, REDUCE, 7}, },
			{{-1, REDUCE, 9}, },
			{{-1, REDUCE, 10}, },
			{{-1, REDUCE, 11}, },
        };*/
    private static int[][][] gotoTable;
/*      {
			{{-1, 2}, },
			{{-1, 3}, },
			{{-1, 8}, },
			{{-1, 9}, {8, 19}, },
			{{-1, 10}, {8, 20}, {9, 21}, {19, 27}, },
			{{-1, 13}, {16, 24}, {17, 25}, {18, 26}, },
			{{-1, 14}, {15, 23}, },
			{{-1, 15}, },
        };*/
    private static String[] errorMessages;
/*      {
			"expecting: 'Title:'",
			"expecting: ' '",
			"expecting: EOF",
			"expecting: 'As a', 'I want', 'So that', EOF",
			"expecting: ' ', word",
			"expecting: 'I want', 'So that', EOF",
			"expecting: 'So that', EOF",
			"expecting: ' ', word, endl",
			"expecting: endl",
        };*/
    private static int[] errors;
/*      {
			0, 1, 2, 3, 4, 1, 1, 1, 5, 6, 2, 7, 7, 8, 7, 7, 4, 4, 4, 6, 2, 2, 3, 7, 8, 8, 8, 2, 5, 6, 2, 
        };*/

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Parser.class.getResourceAsStream("parser.dat")));

            // read actionTable
            int length = s.readInt();
            actionTable = new int[length][][];
            for(int i = 0; i < actionTable.length; i++)
            {
                length = s.readInt();
                actionTable[i] = new int[length][3];
                for(int j = 0; j < actionTable[i].length; j++)
                {
                for(int k = 0; k < 3; k++)
                {
                    actionTable[i][j][k] = s.readInt();
                }
                }
            }

            // read gotoTable
            length = s.readInt();
            gotoTable = new int[length][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][2];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                for(int k = 0; k < 2; k++)
                {
                    gotoTable[i][j][k] = s.readInt();
                }
                }
            }

            // read errorMessages
            length = s.readInt();
            errorMessages = new String[length];
            for(int i = 0; i < errorMessages.length; i++)
            {
                length = s.readInt();
                StringBuffer buffer = new StringBuffer();

                for(int j = 0; j < length; j++)
                {
                buffer.append(s.readChar());
                }
                errorMessages[i] = buffer.toString();
            }

            // read errors
            length = s.readInt();
            errors = new int[length];
            for(int i = 0; i < errors.length; i++)
            {
                errors[i] = s.readInt();
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"parser.dat\" is either missing or corrupted.");
        }
    }
}
