/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.jbehave.core.story.codegen.sablecc.node;

import org.jbehave.core.story.codegen.sablecc.analysis.Analysis;

public final class TThen extends Token
{
    public TThen()
    {
        super.setText("Then");
    }

    public TThen(int line, int pos)
    {
        super.setText("Then");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TThen(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTThen(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TThen text.");
    }
}
