/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.jbehave.core.story.codegen.sablecc.node;

import java.util.*;
import org.jbehave.core.story.codegen.sablecc.analysis.*;

public final class APackage extends PPackage
{
    private TPackageKeyword _packageKeyword_;
    private TSpace _space_;
    private TPackageName _packageName_;
    private TEndl _endl_;

    public APackage()
    {
    }

    public APackage(
        TPackageKeyword _packageKeyword_,
        TSpace _space_,
        TPackageName _packageName_,
        TEndl _endl_)
    {
        setPackageKeyword(_packageKeyword_);

        setSpace(_space_);

        setPackageName(_packageName_);

        setEndl(_endl_);

    }
    public Object clone()
    {
        return new APackage(
            (TPackageKeyword) cloneNode(_packageKeyword_),
            (TSpace) cloneNode(_space_),
            (TPackageName) cloneNode(_packageName_),
            (TEndl) cloneNode(_endl_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPackage(this);
    }

    public TPackageKeyword getPackageKeyword()
    {
        return _packageKeyword_;
    }

    public void setPackageKeyword(TPackageKeyword node)
    {
        if(_packageKeyword_ != null)
        {
            _packageKeyword_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _packageKeyword_ = node;
    }

    public TSpace getSpace()
    {
        return _space_;
    }

    public void setSpace(TSpace node)
    {
        if(_space_ != null)
        {
            _space_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _space_ = node;
    }

    public TPackageName getPackageName()
    {
        return _packageName_;
    }

    public void setPackageName(TPackageName node)
    {
        if(_packageName_ != null)
        {
            _packageName_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _packageName_ = node;
    }

    public TEndl getEndl()
    {
        return _endl_;
    }

    public void setEndl(TEndl node)
    {
        if(_endl_ != null)
        {
            _endl_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _endl_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_packageKeyword_)
            + toString(_space_)
            + toString(_packageName_)
            + toString(_endl_);
    }

    void removeChild(Node child)
    {
        if(_packageKeyword_ == child)
        {
            _packageKeyword_ = null;
            return;
        }

        if(_space_ == child)
        {
            _space_ = null;
            return;
        }

        if(_packageName_ == child)
        {
            _packageName_ = null;
            return;
        }

        if(_endl_ == child)
        {
            _endl_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_packageKeyword_ == oldChild)
        {
            setPackageKeyword((TPackageKeyword) newChild);
            return;
        }

        if(_space_ == oldChild)
        {
            setSpace((TSpace) newChild);
            return;
        }

        if(_packageName_ == oldChild)
        {
            setPackageName((TPackageName) newChild);
            return;
        }

        if(_endl_ == oldChild)
        {
            setEndl((TEndl) newChild);
            return;
        }

    }
}
