/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.jbehave.core.story.codegen.sablecc.node;

import org.jbehave.core.story.codegen.sablecc.analysis.*;

public final class TWhen extends Token
{
    public TWhen()
    {
        super.setText("When");
    }

    public TWhen(int line, int pos)
    {
        super.setText("When");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TWhen(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTWhen(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TWhen text.");
    }
}
