/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.thoughtworks.jbehave.story.codegen.sablecc.parser;

import java.io.BufferedInputStream;
import java.io.DataInputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import java.util.ListIterator;

import com.thoughtworks.jbehave.story.codegen.sablecc.analysis.Analysis;
import com.thoughtworks.jbehave.story.codegen.sablecc.analysis.AnalysisAdapter;
import com.thoughtworks.jbehave.story.codegen.sablecc.lexer.Lexer;
import com.thoughtworks.jbehave.story.codegen.sablecc.lexer.LexerException;
import com.thoughtworks.jbehave.story.codegen.sablecc.node.ABenefit;
import com.thoughtworks.jbehave.story.codegen.sablecc.node.AFeature;
import com.thoughtworks.jbehave.story.codegen.sablecc.node.APhrase;
import com.thoughtworks.jbehave.story.codegen.sablecc.node.ARole;
import com.thoughtworks.jbehave.story.codegen.sablecc.node.AScenario;
import com.thoughtworks.jbehave.story.codegen.sablecc.node.AScenarioTitle;
import com.thoughtworks.jbehave.story.codegen.sablecc.node.ASpaceWordOrSpace;
import com.thoughtworks.jbehave.story.codegen.sablecc.node.AStory;
import com.thoughtworks.jbehave.story.codegen.sablecc.node.ATitle;
import com.thoughtworks.jbehave.story.codegen.sablecc.node.AWordWordOrSpace;
import com.thoughtworks.jbehave.story.codegen.sablecc.node.EOF;
import com.thoughtworks.jbehave.story.codegen.sablecc.node.NodeCast;
import com.thoughtworks.jbehave.story.codegen.sablecc.node.PBenefit;
import com.thoughtworks.jbehave.story.codegen.sablecc.node.PFeature;
import com.thoughtworks.jbehave.story.codegen.sablecc.node.PPhrase;
import com.thoughtworks.jbehave.story.codegen.sablecc.node.PRole;
import com.thoughtworks.jbehave.story.codegen.sablecc.node.PScenario;
import com.thoughtworks.jbehave.story.codegen.sablecc.node.PScenarioTitle;
import com.thoughtworks.jbehave.story.codegen.sablecc.node.PStory;
import com.thoughtworks.jbehave.story.codegen.sablecc.node.PTitle;
import com.thoughtworks.jbehave.story.codegen.sablecc.node.PWordOrSpace;
import com.thoughtworks.jbehave.story.codegen.sablecc.node.Start;
import com.thoughtworks.jbehave.story.codegen.sablecc.node.Switchable;
import com.thoughtworks.jbehave.story.codegen.sablecc.node.TAsA;
import com.thoughtworks.jbehave.story.codegen.sablecc.node.TEndl;
import com.thoughtworks.jbehave.story.codegen.sablecc.node.TIWant;
import com.thoughtworks.jbehave.story.codegen.sablecc.node.TScenarioKeyword;
import com.thoughtworks.jbehave.story.codegen.sablecc.node.TSoThat;
import com.thoughtworks.jbehave.story.codegen.sablecc.node.TSpace;
import com.thoughtworks.jbehave.story.codegen.sablecc.node.TTitleKeyword;
import com.thoughtworks.jbehave.story.codegen.sablecc.node.TWord;
import com.thoughtworks.jbehave.story.codegen.sablecc.node.Token;
import com.thoughtworks.jbehave.story.codegen.sablecc.node.TypedLinkedList;

public class Parser
{
    public final Analysis ignoredTokens = new AnalysisAdapter();

    protected ArrayList nodeList;

    private final Lexer lexer;
    private final ListIterator stack = new LinkedList().listIterator();
    private int last_pos;
    private int last_line;
    private Token last_token;
    private final TokenIndex converter = new TokenIndex();
    private final int[] action = new int[2];

    private final static int SHIFT = 0;
    private final static int REDUCE = 1;
    private final static int ACCEPT = 2;
    private final static int ERROR = 3;

    public Parser(Lexer lexer)
    {
        this.lexer = lexer;
    }

    protected void filter() throws ParserException, LexerException, IOException
    {
    }

    private void push(int numstate, ArrayList listNode, boolean hidden) throws ParserException, LexerException, IOException
    {
	this.nodeList = listNode;

        if(!hidden)
        {
            filter();
        }

        if(!stack.hasNext())
        {
            stack.add(new State(numstate, this.nodeList));
            return;
        }

        State s = (State) stack.next();
        s.state = numstate;
        s.nodes = this.nodeList;
    }

    private int goTo(int index)
    {
        int state = state();
        int low = 1;
        int high = gotoTable[index].length - 1;
        int value = gotoTable[index][0][1];

        while(low <= high)
        {
            int middle = (low + high) / 2;

            if(state < gotoTable[index][middle][0])
            {
                high = middle - 1;
            }
            else if(state > gotoTable[index][middle][0])
            {
                low = middle + 1;
            }
            else
            {
                value = gotoTable[index][middle][1];
                break;
            }
        }

        return value;
    }

    private int state()
    {
        State s = (State) stack.previous();
        stack.next();
        return s.state;
    }

    private ArrayList pop()
    {
        return (ArrayList) ((State) stack.previous()).nodes;
    }

    private int index(Switchable token)
    {
        converter.index = -1;
        token.apply(converter);
        return converter.index;
    }

    public Start parse() throws ParserException, LexerException, IOException
    {
        push(0, null, true);
        List ign = null;
        while(true)
        {
            while(index(lexer.peek()) == -1)
            {
                if(ign == null)
                {
                    ign = new TypedLinkedList(NodeCast.instance);
                }

                ign.add(lexer.next());
            }

            if(ign != null)
            {
                ignoredTokens.setIn(lexer.peek(), ign);
                ign = null;
            }

            last_pos = lexer.peek().getPos();
            last_line = lexer.peek().getLine();
            last_token = lexer.peek();

            int index = index(lexer.peek());
            action[0] = actionTable[state()][0][1];
            action[1] = actionTable[state()][0][2];

            int low = 1;
            int high = actionTable[state()].length - 1;

            while(low <= high)
            {
                int middle = (low + high) / 2;

                if(index < actionTable[state()][middle][0])
                {
                    high = middle - 1;
                }
                else if(index > actionTable[state()][middle][0])
                {
                    low = middle + 1;
                }
                else
                {
                    action[0] = actionTable[state()][middle][1];
                    action[1] = actionTable[state()][middle][2];
                    break;
                }
            }

            switch(action[0])
            {
                case SHIFT:
		    {
		        ArrayList list = new ArrayList();
		        list.add(lexer.next());
                        push(action[1], list, false);
                    }
		    break;
                case REDUCE:
                    switch(action[1])
                    {
                    case 0: /* reduce AAstory1Story */
		    {
			ArrayList list = new0();
			push(goTo(0), list, false);
		    }
		    break;
                    case 1: /* reduce AAstory2Story */
		    {
			ArrayList list = new1();
			push(goTo(0), list, false);
		    }
		    break;
                    case 2: /* reduce AAstory3Story */
		    {
			ArrayList list = new2();
			push(goTo(0), list, false);
		    }
		    break;
                    case 3: /* reduce AAstory4Story */
		    {
			ArrayList list = new3();
			push(goTo(0), list, false);
		    }
		    break;
                    case 4: /* reduce AAstory5Story */
		    {
			ArrayList list = new4();
			push(goTo(0), list, false);
		    }
		    break;
                    case 5: /* reduce AAstory6Story */
		    {
			ArrayList list = new5();
			push(goTo(0), list, false);
		    }
		    break;
                    case 6: /* reduce AAstory7Story */
		    {
			ArrayList list = new6();
			push(goTo(0), list, false);
		    }
		    break;
                    case 7: /* reduce AAstory8Story */
		    {
			ArrayList list = new7();
			push(goTo(0), list, false);
		    }
		    break;
                    case 8: /* reduce AAstory9Story */
		    {
			ArrayList list = new8();
			push(goTo(0), list, false);
		    }
		    break;
                    case 9: /* reduce AAstory10Story */
		    {
			ArrayList list = new9();
			push(goTo(0), list, false);
		    }
		    break;
                    case 10: /* reduce AAstory11Story */
		    {
			ArrayList list = new10();
			push(goTo(0), list, false);
		    }
		    break;
                    case 11: /* reduce AAstory12Story */
		    {
			ArrayList list = new11();
			push(goTo(0), list, false);
		    }
		    break;
                    case 12: /* reduce AAstory13Story */
		    {
			ArrayList list = new12();
			push(goTo(0), list, false);
		    }
		    break;
                    case 13: /* reduce AAstory14Story */
		    {
			ArrayList list = new13();
			push(goTo(0), list, false);
		    }
		    break;
                    case 14: /* reduce AAstory15Story */
		    {
			ArrayList list = new14();
			push(goTo(0), list, false);
		    }
		    break;
                    case 15: /* reduce AAstory16Story */
		    {
			ArrayList list = new15();
			push(goTo(0), list, false);
		    }
		    break;
                    case 16: /* reduce ATitle */
		    {
			ArrayList list = new16();
			push(goTo(1), list, false);
		    }
		    break;
                    case 17: /* reduce ARole */
		    {
			ArrayList list = new17();
			push(goTo(2), list, false);
		    }
		    break;
                    case 18: /* reduce AFeature */
		    {
			ArrayList list = new18();
			push(goTo(3), list, false);
		    }
		    break;
                    case 19: /* reduce ABenefit */
		    {
			ArrayList list = new19();
			push(goTo(4), list, false);
		    }
		    break;
                    case 20: /* reduce AScenario */
		    {
			ArrayList list = new20();
			push(goTo(5), list, false);
		    }
		    break;
                    case 21: /* reduce AScenarioTitle */
		    {
			ArrayList list = new21();
			push(goTo(6), list, false);
		    }
		    break;
                    case 22: /* reduce APhrase */
		    {
			ArrayList list = new22();
			push(goTo(7), list, false);
		    }
		    break;
                    case 23: /* reduce AWordWordOrSpace */
		    {
			ArrayList list = new23();
			push(goTo(8), list, false);
		    }
		    break;
                    case 24: /* reduce ASpaceWordOrSpace */
		    {
			ArrayList list = new24();
			push(goTo(8), list, false);
		    }
		    break;
                    case 25: /* reduce ATerminal$Scenario */
		    {
			ArrayList list = new25();
			push(goTo(9), list, true);
		    }
		    break;
                    case 26: /* reduce ANonTerminal$Scenario */
		    {
			ArrayList list = new26();
			push(goTo(9), list, true);
		    }
		    break;
                    case 27: /* reduce ATerminal$WordOrSpace */
		    {
			ArrayList list = new27();
			push(goTo(10), list, true);
		    }
		    break;
                    case 28: /* reduce ANonTerminal$WordOrSpace */
		    {
			ArrayList list = new28();
			push(goTo(10), list, true);
		    }
		    break;
                    }
                    break;
                case ACCEPT:
                    {
                        EOF node2 = (EOF) lexer.next();
                        PStory node1 = (PStory) ((ArrayList)pop()).get(0);
                        Start node = new Start(node1, node2);
                        return node;
                    }
                case ERROR:
                    throw new ParserException(last_token,
                        "[" + last_line + "," + last_pos + "] " +
                        errorMessages[errors[action[1]]]);
            }
        }
    }



    ArrayList new0() /* reduce AAstory1Story */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStory pstoryNode1;
        {
        PTitle ptitleNode2;
        TypedLinkedList listNode6 = new TypedLinkedList();
        ptitleNode2 = (PTitle)nodeArrayList1.get(0);
        {
        }

        pstoryNode1 = new AStory(ptitleNode2, null, null, null, listNode6);
        }
	nodeList.add(pstoryNode1);
        return nodeList;
    }



    ArrayList new1() /* reduce AAstory2Story */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStory pstoryNode1;
        {
        PTitle ptitleNode2;
        PRole proleNode3;
        TypedLinkedList listNode6 = new TypedLinkedList();
        ptitleNode2 = (PTitle)nodeArrayList1.get(0);
        proleNode3 = (PRole)nodeArrayList2.get(0);
        {
        }

        pstoryNode1 = new AStory(ptitleNode2, proleNode3, null, null, listNode6);
        }
	nodeList.add(pstoryNode1);
        return nodeList;
    }



    ArrayList new2() /* reduce AAstory3Story */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStory pstoryNode1;
        {
        PTitle ptitleNode2;
        PFeature pfeatureNode4;
        TypedLinkedList listNode6 = new TypedLinkedList();
        ptitleNode2 = (PTitle)nodeArrayList1.get(0);
        pfeatureNode4 = (PFeature)nodeArrayList2.get(0);
        {
        }

        pstoryNode1 = new AStory(ptitleNode2, null, pfeatureNode4, null, listNode6);
        }
	nodeList.add(pstoryNode1);
        return nodeList;
    }



    ArrayList new3() /* reduce AAstory4Story */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStory pstoryNode1;
        {
        PTitle ptitleNode2;
        PRole proleNode3;
        PFeature pfeatureNode4;
        TypedLinkedList listNode6 = new TypedLinkedList();
        ptitleNode2 = (PTitle)nodeArrayList1.get(0);
        proleNode3 = (PRole)nodeArrayList2.get(0);
        pfeatureNode4 = (PFeature)nodeArrayList3.get(0);
        {
        }

        pstoryNode1 = new AStory(ptitleNode2, proleNode3, pfeatureNode4, null, listNode6);
        }
	nodeList.add(pstoryNode1);
        return nodeList;
    }



    ArrayList new4() /* reduce AAstory5Story */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStory pstoryNode1;
        {
        PTitle ptitleNode2;
        PBenefit pbenefitNode5;
        TypedLinkedList listNode6 = new TypedLinkedList();
        ptitleNode2 = (PTitle)nodeArrayList1.get(0);
        pbenefitNode5 = (PBenefit)nodeArrayList2.get(0);
        {
        }

        pstoryNode1 = new AStory(ptitleNode2, null, null, pbenefitNode5, listNode6);
        }
	nodeList.add(pstoryNode1);
        return nodeList;
    }



    ArrayList new5() /* reduce AAstory6Story */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStory pstoryNode1;
        {
        PTitle ptitleNode2;
        PRole proleNode3;
        PBenefit pbenefitNode5;
        TypedLinkedList listNode6 = new TypedLinkedList();
        ptitleNode2 = (PTitle)nodeArrayList1.get(0);
        proleNode3 = (PRole)nodeArrayList2.get(0);
        pbenefitNode5 = (PBenefit)nodeArrayList3.get(0);
        {
        }

        pstoryNode1 = new AStory(ptitleNode2, proleNode3, null, pbenefitNode5, listNode6);
        }
	nodeList.add(pstoryNode1);
        return nodeList;
    }



    ArrayList new6() /* reduce AAstory7Story */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStory pstoryNode1;
        {
        PTitle ptitleNode2;
        PFeature pfeatureNode4;
        PBenefit pbenefitNode5;
        TypedLinkedList listNode6 = new TypedLinkedList();
        ptitleNode2 = (PTitle)nodeArrayList1.get(0);
        pfeatureNode4 = (PFeature)nodeArrayList2.get(0);
        pbenefitNode5 = (PBenefit)nodeArrayList3.get(0);
        {
        }

        pstoryNode1 = new AStory(ptitleNode2, null, pfeatureNode4, pbenefitNode5, listNode6);
        }
	nodeList.add(pstoryNode1);
        return nodeList;
    }



    ArrayList new7() /* reduce AAstory8Story */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStory pstoryNode1;
        {
        PTitle ptitleNode2;
        PRole proleNode3;
        PFeature pfeatureNode4;
        PBenefit pbenefitNode5;
        TypedLinkedList listNode6 = new TypedLinkedList();
        ptitleNode2 = (PTitle)nodeArrayList1.get(0);
        proleNode3 = (PRole)nodeArrayList2.get(0);
        pfeatureNode4 = (PFeature)nodeArrayList3.get(0);
        pbenefitNode5 = (PBenefit)nodeArrayList4.get(0);
        {
        }

        pstoryNode1 = new AStory(ptitleNode2, proleNode3, pfeatureNode4, pbenefitNode5, listNode6);
        }
	nodeList.add(pstoryNode1);
        return nodeList;
    }



    ArrayList new8() /* reduce AAstory9Story */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStory pstoryNode1;
        {
        PTitle ptitleNode2;
        TypedLinkedList listNode7 = new TypedLinkedList();
        ptitleNode2 = (PTitle)nodeArrayList1.get(0);
        {
        TypedLinkedList listNode6 = new TypedLinkedList();
        listNode6 = (TypedLinkedList)nodeArrayList2.get(0);
	if(listNode6 != null)
	{
	  listNode7.addAll(listNode6);
	}
        }

        pstoryNode1 = new AStory(ptitleNode2, null, null, null, listNode7);
        }
	nodeList.add(pstoryNode1);
        return nodeList;
    }



    ArrayList new9() /* reduce AAstory10Story */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStory pstoryNode1;
        {
        PTitle ptitleNode2;
        PRole proleNode3;
        TypedLinkedList listNode7 = new TypedLinkedList();
        ptitleNode2 = (PTitle)nodeArrayList1.get(0);
        proleNode3 = (PRole)nodeArrayList2.get(0);
        {
        TypedLinkedList listNode6 = new TypedLinkedList();
        listNode6 = (TypedLinkedList)nodeArrayList3.get(0);
	if(listNode6 != null)
	{
	  listNode7.addAll(listNode6);
	}
        }

        pstoryNode1 = new AStory(ptitleNode2, proleNode3, null, null, listNode7);
        }
	nodeList.add(pstoryNode1);
        return nodeList;
    }



    ArrayList new10() /* reduce AAstory11Story */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStory pstoryNode1;
        {
        PTitle ptitleNode2;
        PFeature pfeatureNode4;
        TypedLinkedList listNode7 = new TypedLinkedList();
        ptitleNode2 = (PTitle)nodeArrayList1.get(0);
        pfeatureNode4 = (PFeature)nodeArrayList2.get(0);
        {
        TypedLinkedList listNode6 = new TypedLinkedList();
        listNode6 = (TypedLinkedList)nodeArrayList3.get(0);
	if(listNode6 != null)
	{
	  listNode7.addAll(listNode6);
	}
        }

        pstoryNode1 = new AStory(ptitleNode2, null, pfeatureNode4, null, listNode7);
        }
	nodeList.add(pstoryNode1);
        return nodeList;
    }



    ArrayList new11() /* reduce AAstory12Story */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStory pstoryNode1;
        {
        PTitle ptitleNode2;
        PRole proleNode3;
        PFeature pfeatureNode4;
        TypedLinkedList listNode7 = new TypedLinkedList();
        ptitleNode2 = (PTitle)nodeArrayList1.get(0);
        proleNode3 = (PRole)nodeArrayList2.get(0);
        pfeatureNode4 = (PFeature)nodeArrayList3.get(0);
        {
        TypedLinkedList listNode6 = new TypedLinkedList();
        listNode6 = (TypedLinkedList)nodeArrayList4.get(0);
	if(listNode6 != null)
	{
	  listNode7.addAll(listNode6);
	}
        }

        pstoryNode1 = new AStory(ptitleNode2, proleNode3, pfeatureNode4, null, listNode7);
        }
	nodeList.add(pstoryNode1);
        return nodeList;
    }



    ArrayList new12() /* reduce AAstory13Story */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStory pstoryNode1;
        {
        PTitle ptitleNode2;
        PBenefit pbenefitNode5;
        TypedLinkedList listNode7 = new TypedLinkedList();
        ptitleNode2 = (PTitle)nodeArrayList1.get(0);
        pbenefitNode5 = (PBenefit)nodeArrayList2.get(0);
        {
        TypedLinkedList listNode6 = new TypedLinkedList();
        listNode6 = (TypedLinkedList)nodeArrayList3.get(0);
	if(listNode6 != null)
	{
	  listNode7.addAll(listNode6);
	}
        }

        pstoryNode1 = new AStory(ptitleNode2, null, null, pbenefitNode5, listNode7);
        }
	nodeList.add(pstoryNode1);
        return nodeList;
    }



    ArrayList new13() /* reduce AAstory14Story */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStory pstoryNode1;
        {
        PTitle ptitleNode2;
        PRole proleNode3;
        PBenefit pbenefitNode5;
        TypedLinkedList listNode7 = new TypedLinkedList();
        ptitleNode2 = (PTitle)nodeArrayList1.get(0);
        proleNode3 = (PRole)nodeArrayList2.get(0);
        pbenefitNode5 = (PBenefit)nodeArrayList3.get(0);
        {
        TypedLinkedList listNode6 = new TypedLinkedList();
        listNode6 = (TypedLinkedList)nodeArrayList4.get(0);
	if(listNode6 != null)
	{
	  listNode7.addAll(listNode6);
	}
        }

        pstoryNode1 = new AStory(ptitleNode2, proleNode3, null, pbenefitNode5, listNode7);
        }
	nodeList.add(pstoryNode1);
        return nodeList;
    }



    ArrayList new14() /* reduce AAstory15Story */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStory pstoryNode1;
        {
        PTitle ptitleNode2;
        PFeature pfeatureNode4;
        PBenefit pbenefitNode5;
        TypedLinkedList listNode7 = new TypedLinkedList();
        ptitleNode2 = (PTitle)nodeArrayList1.get(0);
        pfeatureNode4 = (PFeature)nodeArrayList2.get(0);
        pbenefitNode5 = (PBenefit)nodeArrayList3.get(0);
        {
        TypedLinkedList listNode6 = new TypedLinkedList();
        listNode6 = (TypedLinkedList)nodeArrayList4.get(0);
	if(listNode6 != null)
	{
	  listNode7.addAll(listNode6);
	}
        }

        pstoryNode1 = new AStory(ptitleNode2, null, pfeatureNode4, pbenefitNode5, listNode7);
        }
	nodeList.add(pstoryNode1);
        return nodeList;
    }



    ArrayList new15() /* reduce AAstory16Story */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStory pstoryNode1;
        {
        PTitle ptitleNode2;
        PRole proleNode3;
        PFeature pfeatureNode4;
        PBenefit pbenefitNode5;
        TypedLinkedList listNode7 = new TypedLinkedList();
        ptitleNode2 = (PTitle)nodeArrayList1.get(0);
        proleNode3 = (PRole)nodeArrayList2.get(0);
        pfeatureNode4 = (PFeature)nodeArrayList3.get(0);
        pbenefitNode5 = (PBenefit)nodeArrayList4.get(0);
        {
        TypedLinkedList listNode6 = new TypedLinkedList();
        listNode6 = (TypedLinkedList)nodeArrayList5.get(0);
	if(listNode6 != null)
	{
	  listNode7.addAll(listNode6);
	}
        }

        pstoryNode1 = new AStory(ptitleNode2, proleNode3, pfeatureNode4, pbenefitNode5, listNode7);
        }
	nodeList.add(pstoryNode1);
        return nodeList;
    }



    ArrayList new16() /* reduce ATitle */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PTitle ptitleNode1;
        {
        TTitleKeyword ttitlekeywordNode2;
        TSpace tspaceNode3;
        PPhrase pphraseNode4;
        TEndl tendlNode5;
        ttitlekeywordNode2 = (TTitleKeyword)nodeArrayList1.get(0);
        tspaceNode3 = (TSpace)nodeArrayList2.get(0);
        pphraseNode4 = (PPhrase)nodeArrayList3.get(0);
        tendlNode5 = (TEndl)nodeArrayList4.get(0);

        ptitleNode1 = new ATitle(ttitlekeywordNode2, tspaceNode3, pphraseNode4, tendlNode5);
        }
	nodeList.add(ptitleNode1);
        return nodeList;
    }



    ArrayList new17() /* reduce ARole */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PRole proleNode1;
        {
        TAsA tasaNode2;
        TSpace tspaceNode3;
        PPhrase pphraseNode4;
        TEndl tendlNode5;
        tasaNode2 = (TAsA)nodeArrayList1.get(0);
        tspaceNode3 = (TSpace)nodeArrayList2.get(0);
        pphraseNode4 = (PPhrase)nodeArrayList3.get(0);
        tendlNode5 = (TEndl)nodeArrayList4.get(0);

        proleNode1 = new ARole(tasaNode2, tspaceNode3, pphraseNode4, tendlNode5);
        }
	nodeList.add(proleNode1);
        return nodeList;
    }



    ArrayList new18() /* reduce AFeature */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PFeature pfeatureNode1;
        {
        TIWant tiwantNode2;
        TSpace tspaceNode3;
        PPhrase pphraseNode4;
        TEndl tendlNode5;
        tiwantNode2 = (TIWant)nodeArrayList1.get(0);
        tspaceNode3 = (TSpace)nodeArrayList2.get(0);
        pphraseNode4 = (PPhrase)nodeArrayList3.get(0);
        tendlNode5 = (TEndl)nodeArrayList4.get(0);

        pfeatureNode1 = new AFeature(tiwantNode2, tspaceNode3, pphraseNode4, tendlNode5);
        }
	nodeList.add(pfeatureNode1);
        return nodeList;
    }



    ArrayList new19() /* reduce ABenefit */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PBenefit pbenefitNode1;
        {
        TSoThat tsothatNode2;
        TSpace tspaceNode3;
        PPhrase pphraseNode4;
        TEndl tendlNode5;
        tsothatNode2 = (TSoThat)nodeArrayList1.get(0);
        tspaceNode3 = (TSpace)nodeArrayList2.get(0);
        pphraseNode4 = (PPhrase)nodeArrayList3.get(0);
        tendlNode5 = (TEndl)nodeArrayList4.get(0);

        pbenefitNode1 = new ABenefit(tsothatNode2, tspaceNode3, pphraseNode4, tendlNode5);
        }
	nodeList.add(pbenefitNode1);
        return nodeList;
    }



    ArrayList new20() /* reduce AScenario */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PScenario pscenarioNode1;
        {
        PScenarioTitle pscenariotitleNode2;
        pscenariotitleNode2 = (PScenarioTitle)nodeArrayList1.get(0);

        pscenarioNode1 = new AScenario(pscenariotitleNode2);
        }
	nodeList.add(pscenarioNode1);
        return nodeList;
    }



    ArrayList new21() /* reduce AScenarioTitle */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PScenarioTitle pscenariotitleNode1;
        {
        TScenarioKeyword tscenariokeywordNode2;
        TSpace tspaceNode3;
        PPhrase pphraseNode4;
        TEndl tendlNode5;
        tscenariokeywordNode2 = (TScenarioKeyword)nodeArrayList1.get(0);
        tspaceNode3 = (TSpace)nodeArrayList2.get(0);
        pphraseNode4 = (PPhrase)nodeArrayList3.get(0);
        tendlNode5 = (TEndl)nodeArrayList4.get(0);

        pscenariotitleNode1 = new AScenarioTitle(tscenariokeywordNode2, tspaceNode3, pphraseNode4, tendlNode5);
        }
	nodeList.add(pscenariotitleNode1);
        return nodeList;
    }



    ArrayList new22() /* reduce APhrase */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PPhrase pphraseNode1;
        {
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        TypedLinkedList listNode2 = new TypedLinkedList();
        listNode2 = (TypedLinkedList)nodeArrayList1.get(0);
	if(listNode2 != null)
	{
	  listNode3.addAll(listNode2);
	}
        }

        pphraseNode1 = new APhrase(listNode3);
        }
	nodeList.add(pphraseNode1);
        return nodeList;
    }



    ArrayList new23() /* reduce AWordWordOrSpace */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PWordOrSpace pwordorspaceNode1;
        {
        TWord twordNode2;
        twordNode2 = (TWord)nodeArrayList1.get(0);

        pwordorspaceNode1 = new AWordWordOrSpace(twordNode2);
        }
	nodeList.add(pwordorspaceNode1);
        return nodeList;
    }



    ArrayList new24() /* reduce ASpaceWordOrSpace */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PWordOrSpace pwordorspaceNode1;
        {
        TSpace tspaceNode2;
        tspaceNode2 = (TSpace)nodeArrayList1.get(0);

        pwordorspaceNode1 = new ASpaceWordOrSpace(tspaceNode2);
        }
	nodeList.add(pwordorspaceNode1);
        return nodeList;
    }



    ArrayList new25() /* reduce ATerminal$Scenario */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode2 = new TypedLinkedList();
        {
        PScenario pscenarioNode1;
        pscenarioNode1 = (PScenario)nodeArrayList1.get(0);
	if(pscenarioNode1 != null)
	{
	  listNode2.add(pscenarioNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    ArrayList new26() /* reduce ANonTerminal$Scenario */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        TypedLinkedList listNode1 = new TypedLinkedList();
        PScenario pscenarioNode2;
        listNode1 = (TypedLinkedList)nodeArrayList1.get(0);
        pscenarioNode2 = (PScenario)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pscenarioNode2 != null)
	{
	  listNode3.add(pscenarioNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    ArrayList new27() /* reduce ATerminal$WordOrSpace */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode2 = new TypedLinkedList();
        {
        PWordOrSpace pwordorspaceNode1;
        pwordorspaceNode1 = (PWordOrSpace)nodeArrayList1.get(0);
	if(pwordorspaceNode1 != null)
	{
	  listNode2.add(pwordorspaceNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    ArrayList new28() /* reduce ANonTerminal$WordOrSpace */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        TypedLinkedList listNode1 = new TypedLinkedList();
        PWordOrSpace pwordorspaceNode2;
        listNode1 = (TypedLinkedList)nodeArrayList1.get(0);
        pwordorspaceNode2 = (PWordOrSpace)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pwordorspaceNode2 != null)
	{
	  listNode3.add(pwordorspaceNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    private static int[][][] actionTable;
/*      {
			{{-1, ERROR, 0}, {0, SHIFT, 1}, },
			{{-1, ERROR, 1}, {5, SHIFT, 4}, },
			{{-1, ERROR, 2}, {8, ACCEPT, -1}, },
			{{-1, REDUCE, 0}, {1, SHIFT, 5}, {2, SHIFT, 6}, {3, SHIFT, 7}, {4, SHIFT, 8}, },
			{{-1, ERROR, 4}, {5, SHIFT, 15}, {6, SHIFT, 16}, },
			{{-1, ERROR, 5}, {5, SHIFT, 20}, },
			{{-1, ERROR, 6}, {5, SHIFT, 21}, },
			{{-1, ERROR, 7}, {5, SHIFT, 22}, },
			{{-1, ERROR, 8}, {5, SHIFT, 23}, },
			{{-1, REDUCE, 1}, {1, SHIFT, 5}, {3, SHIFT, 7}, {4, SHIFT, 8}, },
			{{-1, REDUCE, 2}, {1, SHIFT, 5}, {4, SHIFT, 8}, },
			{{-1, REDUCE, 4}, {1, SHIFT, 5}, },
			{{-1, REDUCE, 25}, },
			{{-1, REDUCE, 20}, },
			{{-1, REDUCE, 8}, {1, SHIFT, 5}, },
			{{-1, REDUCE, 24}, },
			{{-1, REDUCE, 23}, },
			{{-1, ERROR, 17}, {7, SHIFT, 31}, },
			{{-1, REDUCE, 27}, },
			{{-1, REDUCE, 22}, {5, SHIFT, 15}, {6, SHIFT, 16}, },
			{{-1, ERROR, 20}, {5, SHIFT, 15}, {6, SHIFT, 16}, },
			{{-1, ERROR, 21}, {5, SHIFT, 15}, {6, SHIFT, 16}, },
			{{-1, ERROR, 22}, {5, SHIFT, 15}, {6, SHIFT, 16}, },
			{{-1, ERROR, 23}, {5, SHIFT, 15}, {6, SHIFT, 16}, },
			{{-1, REDUCE, 3}, {1, SHIFT, 5}, {4, SHIFT, 8}, },
			{{-1, REDUCE, 5}, {1, SHIFT, 5}, },
			{{-1, REDUCE, 9}, {1, SHIFT, 5}, },
			{{-1, REDUCE, 6}, {1, SHIFT, 5}, },
			{{-1, REDUCE, 10}, {1, SHIFT, 5}, },
			{{-1, REDUCE, 12}, {1, SHIFT, 5}, },
			{{-1, REDUCE, 26}, },
			{{-1, REDUCE, 16}, },
			{{-1, REDUCE, 28}, },
			{{-1, ERROR, 33}, {7, SHIFT, 41}, },
			{{-1, ERROR, 34}, {7, SHIFT, 42}, },
			{{-1, ERROR, 35}, {7, SHIFT, 43}, },
			{{-1, ERROR, 36}, {7, SHIFT, 44}, },
			{{-1, REDUCE, 7}, {1, SHIFT, 5}, },
			{{-1, REDUCE, 11}, {1, SHIFT, 5}, },
			{{-1, REDUCE, 13}, {1, SHIFT, 5}, },
			{{-1, REDUCE, 14}, {1, SHIFT, 5}, },
			{{-1, REDUCE, 21}, },
			{{-1, REDUCE, 17}, },
			{{-1, REDUCE, 18}, },
			{{-1, REDUCE, 19}, },
			{{-1, REDUCE, 15}, {1, SHIFT, 5}, },
        };*/
    private static int[][][] gotoTable;
/*      {
			{{-1, 2}, },
			{{-1, 3}, },
			{{-1, 9}, },
			{{-1, 10}, {9, 24}, },
			{{-1, 11}, {9, 25}, {10, 27}, {24, 37}, },
			{{-1, 12}, {14, 30}, {26, 30}, {28, 30}, {29, 30}, {38, 30}, {39, 30}, {40, 30}, {45, 30}, },
			{{-1, 13}, },
			{{-1, 17}, {20, 33}, {21, 34}, {22, 35}, {23, 36}, },
			{{-1, 18}, {19, 32}, },
			{{-1, 14}, {9, 26}, {10, 28}, {11, 29}, {24, 38}, {25, 39}, {27, 40}, {37, 45}, },
			{{-1, 19}, },
        };*/
    private static String[] errorMessages;
/*      {
			"expecting: 'Title:'",
			"expecting: ' '",
			"expecting: EOF",
			"expecting: 'Scenario:', 'As a', 'I want', 'So that', EOF",
			"expecting: ' ', word",
			"expecting: 'Scenario:', 'I want', 'So that', EOF",
			"expecting: 'Scenario:', 'So that', EOF",
			"expecting: 'Scenario:', EOF",
			"expecting: ' ', word, endl",
			"expecting: endl",
        };*/
    private static int[] errors;
/*      {
			0, 1, 2, 3, 4, 1, 1, 1, 1, 5, 6, 7, 7, 7, 7, 8, 8, 9, 8, 8, 4, 4, 4, 4, 6, 7, 7, 7, 7, 7, 7, 3, 8, 9, 9, 9, 9, 7, 7, 7, 7, 7, 5, 6, 7, 7, 
        };*/

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Parser.class.getResourceAsStream("parser.dat")));

            // read actionTable
            int length = s.readInt();
            actionTable = new int[length][][];
            for(int i = 0; i < actionTable.length; i++)
            {
                length = s.readInt();
                actionTable[i] = new int[length][3];
                for(int j = 0; j < actionTable[i].length; j++)
                {
                for(int k = 0; k < 3; k++)
                {
                    actionTable[i][j][k] = s.readInt();
                }
                }
            }

            // read gotoTable
            length = s.readInt();
            gotoTable = new int[length][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][2];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                for(int k = 0; k < 2; k++)
                {
                    gotoTable[i][j][k] = s.readInt();
                }
                }
            }

            // read errorMessages
            length = s.readInt();
            errorMessages = new String[length];
            for(int i = 0; i < errorMessages.length; i++)
            {
                length = s.readInt();
                StringBuffer buffer = new StringBuffer();

                for(int j = 0; j < length; j++)
                {
                buffer.append(s.readChar());
                }
                errorMessages[i] = buffer.toString();
            }

            // read errors
            length = s.readInt();
            errors = new int[length];
            for(int i = 0; i < errors.length; i++)
            {
                errors[i] = s.readInt();
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"parser.dat\" is either missing or corrupted.");
        }
    }
}
