/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.thoughtworks.jbehave.story.codegen.sablecc.parser;

import com.thoughtworks.jbehave.story.codegen.sablecc.node.*;
import com.thoughtworks.jbehave.story.codegen.sablecc.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    public void caseTTitleKeyword(TTitleKeyword node)
    {
        index = 0;
    }

    public void caseTScenarioKeyword(TScenarioKeyword node)
    {
        index = 1;
    }

    public void caseTAsA(TAsA node)
    {
        index = 2;
    }

    public void caseTIWant(TIWant node)
    {
        index = 3;
    }

    public void caseTSoThat(TSoThat node)
    {
        index = 4;
    }

    public void caseTSpace(TSpace node)
    {
        index = 5;
    }

    public void caseTWord(TWord node)
    {
        index = 6;
    }

    public void caseTEndl(TEndl node)
    {
        index = 7;
    }

    public void caseEOF(EOF node)
    {
        index = 8;
    }
}
