/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.jbehave.core.story.codegen.sablecc.node;

import org.jbehave.core.story.codegen.sablecc.analysis.*;

public final class TGiven extends Token
{
    public TGiven()
    {
        super.setText("Given");
    }

    public TGiven(int line, int pos)
    {
        super.setText("Given");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TGiven(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTGiven(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TGiven text.");
    }
}
